# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\check_reg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_check_reg_app(object):
    def setupUi(self, check_reg_app):
        check_reg_app.setObjectName(_fromUtf8("check_reg_app"))
        check_reg_app.resize(1122, 767)
        self.centralwidget = QtGui.QWidget(check_reg_app)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.control_frame = QtGui.QFrame(self.splitter)
        self.control_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.control_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.control_frame.setObjectName(_fromUtf8("control_frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.control_frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.control_frame)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.subj1 = QtGui.QLineEdit(self.frame)
        self.subj1.setObjectName(_fromUtf8("subj1"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.subj1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.mod1 = QtGui.QComboBox(self.frame)
        self.mod1.setObjectName(_fromUtf8("mod1"))
        self.mod1.addItem(_fromUtf8(""))
        self.mod1.addItem(_fromUtf8(""))
        self.mod1.addItem(_fromUtf8(""))
        self.mod1.addItem(_fromUtf8(""))
        self.mod1.addItem(_fromUtf8(""))
        self.mod1.addItem(_fromUtf8(""))
        self.mod1.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.mod1)
        self.label_5 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.label_5)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.subj2 = QtGui.QLineEdit(self.frame)
        self.subj2.setObjectName(_fromUtf8("subj2"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.subj2)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.mod2 = QtGui.QComboBox(self.frame)
        self.mod2.setObjectName(_fromUtf8("mod2"))
        self.mod2.addItem(_fromUtf8(""))
        self.mod2.addItem(_fromUtf8(""))
        self.mod2.addItem(_fromUtf8(""))
        self.mod2.addItem(_fromUtf8(""))
        self.mod2.addItem(_fromUtf8(""))
        self.mod2.addItem(_fromUtf8(""))
        self.mod2.addItem(_fromUtf8(""))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.mod2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtGui.QFormLayout.LabelRole, spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.control_frame)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.coords_combo = QtGui.QComboBox(self.frame_2)
        self.coords_combo.setObjectName(_fromUtf8("coords_combo"))
        self.coords_combo.addItem(_fromUtf8(""))
        self.coords_combo.addItem(_fromUtf8(""))
        self.coords_combo.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.coords_combo)
        self.orientation_combo = QtGui.QComboBox(self.frame_2)
        self.orientation_combo.setObjectName(_fromUtf8("orientation_combo"))
        self.orientation_combo.addItem(_fromUtf8(""))
        self.orientation_combo.addItem(_fromUtf8(""))
        self.orientation_combo.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.orientation_combo)
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.divisions_box = QtGui.QSpinBox(self.frame_2)
        self.divisions_box.setProperty("value", 3)
        self.divisions_box.setObjectName(_fromUtf8("divisions_box"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.divisions_box)
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_12)
        self.slice_slider = QtGui.QSlider(self.frame_2)
        self.slice_slider.setOrientation(QtCore.Qt.Horizontal)
        self.slice_slider.setObjectName(_fromUtf8("slice_slider"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.SpanningRole, self.slice_slider)
        self.verticalLayout.addWidget(self.frame_2)
        self.vtk_frame = QtGui.QFrame(self.splitter)
        self.vtk_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.vtk_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.vtk_frame.setObjectName(_fromUtf8("vtk_frame"))
        self.horizontalLayout.addWidget(self.splitter)
        check_reg_app.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(check_reg_app)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        check_reg_app.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(check_reg_app)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        check_reg_app.setStatusBar(self.statusbar)

        self.retranslateUi(check_reg_app)
        QtCore.QMetaObject.connectSlotsByName(check_reg_app)

    def retranslateUi(self, check_reg_app):
        check_reg_app.setWindowTitle(_translate("check_reg_app", "Braviz Check Registration", None))
        self.label.setText(_translate("check_reg_app", "Image 1", None))
        self.label_2.setText(_translate("check_reg_app", "Subject", None))
        self.subj1.setText(_translate("check_reg_app", "119", None))
        self.label_3.setText(_translate("check_reg_app", "Modality", None))
        self.mod1.setItemText(0, _translate("check_reg_app", "None", None))
        self.mod1.setItemText(1, _translate("check_reg_app", "MRI", None))
        self.mod1.setItemText(2, _translate("check_reg_app", "FA", None))
        self.mod1.setItemText(3, _translate("check_reg_app", "MD", None))
        self.mod1.setItemText(4, _translate("check_reg_app", "DTI", None))
        self.mod1.setItemText(5, _translate("check_reg_app", "APARC", None))
        self.mod1.setItemText(6, _translate("check_reg_app", "WMPARC", None))
        self.label_5.setText(_translate("check_reg_app", "Image 2", None))
        self.label_7.setText(_translate("check_reg_app", "Subject", None))
        self.subj2.setText(_translate("check_reg_app", "119", None))
        self.label_8.setText(_translate("check_reg_app", "Modality", None))
        self.mod2.setItemText(0, _translate("check_reg_app", "None", None))
        self.mod2.setItemText(1, _translate("check_reg_app", "MRI", None))
        self.mod2.setItemText(2, _translate("check_reg_app", "FA", None))
        self.mod2.setItemText(3, _translate("check_reg_app", "MD", None))
        self.mod2.setItemText(4, _translate("check_reg_app", "DTI", None))
        self.mod2.setItemText(5, _translate("check_reg_app", "APARC", None))
        self.mod2.setItemText(6, _translate("check_reg_app", "WMPARC", None))
        self.label_9.setText(_translate("check_reg_app", "Coordinates", None))
        self.label_10.setText(_translate("check_reg_app", "Orientation", None))
        self.coords_combo.setItemText(0, _translate("check_reg_app", "Subject", None))
        self.coords_combo.setItemText(1, _translate("check_reg_app", "Talairach", None))
        self.coords_combo.setItemText(2, _translate("check_reg_app", "Dartel", None))
        self.orientation_combo.setItemText(0, _translate("check_reg_app", "Axial", None))
        self.orientation_combo.setItemText(1, _translate("check_reg_app", "Coronal", None))
        self.orientation_combo.setItemText(2, _translate("check_reg_app", "Sagital", None))
        self.label_11.setText(_translate("check_reg_app", "Divisions", None))
        self.label_12.setText(_translate("check_reg_app", "Slice:", None))

