# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\correlations.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_correlation_app(object):
    def setupUi(self, correlation_app):
        correlation_app.setObjectName(_fromUtf8("correlation_app"))
        correlation_app.resize(1285, 544)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/correlations_app.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        correlation_app.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(correlation_app)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.list_frame = QtGui.QFrame(self.centralwidget)
        self.list_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.list_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.list_frame.setObjectName(_fromUtf8("list_frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.list_frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.list_frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.search_box = QtGui.QLineEdit(self.list_frame)
        self.search_box.setObjectName(_fromUtf8("search_box"))
        self.verticalLayout.addWidget(self.search_box)
        self.variables_list = QtGui.QListView(self.list_frame)
        self.variables_list.setFrameShape(QtGui.QFrame.NoFrame)
        self.variables_list.setAlternatingRowColors(True)
        self.variables_list.setWordWrap(True)
        self.variables_list.setObjectName(_fromUtf8("variables_list"))
        self.verticalLayout.addWidget(self.variables_list)
        self.horizontalLayout.addWidget(self.list_frame)
        self.cor_mat_frame = QtGui.QFrame(self.centralwidget)
        self.cor_mat_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.cor_mat_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.cor_mat_frame.setObjectName(_fromUtf8("cor_mat_frame"))
        self.horizontalLayout.addWidget(self.cor_mat_frame)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.reg_frame = QtGui.QFrame(self.frame)
        self.reg_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.reg_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.reg_frame.setObjectName(_fromUtf8("reg_frame"))
        self.verticalLayout_2.addWidget(self.reg_frame)
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(18, 0, 18, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.ignored_label = QtGui.QLabel(self.frame_2)
        self.ignored_label.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ignored_label.setFrameShadow(QtGui.QFrame.Sunken)
        self.ignored_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ignored_label.setObjectName(_fromUtf8("ignored_label"))
        self.horizontalLayout_2.addWidget(self.ignored_label)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.restore_points = QtGui.QPushButton(self.frame_2)
        self.restore_points.setObjectName(_fromUtf8("restore_points"))
        self.horizontalLayout_2.addWidget(self.restore_points)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 5)
        correlation_app.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(correlation_app)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1285, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAccept_sample = QtGui.QMenu(self.menuFile)
        self.menuAccept_sample.setObjectName(_fromUtf8("menuAccept_sample"))
        correlation_app.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(correlation_app)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        correlation_app.setStatusBar(self.statusbar)
        self.actionSave_Scenario = QtGui.QAction(correlation_app)
        self.actionSave_Scenario.setObjectName(_fromUtf8("actionSave_Scenario"))
        self.actionLoad_Scenario = QtGui.QAction(correlation_app)
        self.actionLoad_Scenario.setObjectName(_fromUtf8("actionLoad_Scenario"))
        self.actionLoad_sample = QtGui.QAction(correlation_app)
        self.actionLoad_sample.setObjectName(_fromUtf8("actionLoad_sample"))
        self.actionSave_Matrix = QtGui.QAction(correlation_app)
        self.actionSave_Matrix.setObjectName(_fromUtf8("actionSave_Matrix"))
        self.actionSave_Scatter = QtGui.QAction(correlation_app)
        self.actionSave_Scatter.setObjectName(_fromUtf8("actionSave_Scatter"))
        self.actionModify_sample = QtGui.QAction(correlation_app)
        self.actionModify_sample.setObjectName(_fromUtf8("actionModify_sample"))
        self.actionRestore_sample = QtGui.QAction(correlation_app)
        self.actionRestore_sample.setObjectName(_fromUtf8("actionRestore_sample"))
        self.actionSend_sample = QtGui.QAction(correlation_app)
        self.actionSend_sample.setObjectName(_fromUtf8("actionSend_sample"))
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Matrix)
        self.menuFile.addAction(self.actionSave_Scatter)
        self.menuFile.addAction(self.actionSave_Scenario)
        self.menuFile.addAction(self.actionLoad_Scenario)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_sample)
        self.menuFile.addAction(self.actionRestore_sample)
        self.menuFile.addAction(self.actionModify_sample)
        self.menuFile.addAction(self.actionSend_sample)
        self.menuFile.addAction(self.menuAccept_sample.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(correlation_app)
        QtCore.QMetaObject.connectSlotsByName(correlation_app)

    def retranslateUi(self, correlation_app):
        correlation_app.setWindowTitle(_translate("correlation_app", "Correlations", None))
        self.label.setText(_translate("correlation_app", "Select Variables:", None))
        self.search_box.setPlaceholderText(_translate("correlation_app", "Search", None))
        self.ignored_label.setToolTip(_translate("correlation_app", "Click on any point on the plot to temporary ignore it", None))
        self.ignored_label.setText(_translate("correlation_app", "0", None))
        self.label_2.setText(_translate("correlation_app", "Ignored Points", None))
        self.restore_points.setText(_translate("correlation_app", "Restore All Points", None))
        self.menuFile.setTitle(_translate("correlation_app", "File", None))
        self.menuAccept_sample.setTitle(_translate("correlation_app", "Accept sample", None))
        self.actionSave_Scenario.setText(_translate("correlation_app", "Save Scenario", None))
        self.actionLoad_Scenario.setText(_translate("correlation_app", "Load Scenario", None))
        self.actionLoad_sample.setText(_translate("correlation_app", "Load sample", None))
        self.actionSave_Matrix.setText(_translate("correlation_app", "Save Matrix", None))
        self.actionSave_Scatter.setText(_translate("correlation_app", "Save Scatter", None))
        self.actionModify_sample.setText(_translate("correlation_app", "Modify sample", None))
        self.actionRestore_sample.setText(_translate("correlation_app", "Restore sample", None))
        self.actionRestore_sample.setToolTip(_translate("correlation_app", "Restore all emoved points", None))
        self.actionSend_sample.setText(_translate("correlation_app", "Send sample", None))
        self.actionSend_sample.setToolTip(_translate("correlation_app", "Send Sample (removed points will be omited)", None))

import resources_rc
