# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\fmri_explore.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_fMRI_Explorer(object):
    def setupUi(self, fMRI_Explorer):
        fMRI_Explorer.setObjectName(_fromUtf8("fMRI_Explorer"))
        fMRI_Explorer.resize(1128, 701)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/fmri_explore_small.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        fMRI_Explorer.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(fMRI_Explorer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.splitter_2 = QtGui.QSplitter(self.frame_2)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.fMRI = QtGui.QTabWidget(self.splitter)
        self.fMRI.setObjectName(_fromUtf8("fMRI"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.formLayout = QtGui.QFormLayout(self.tab)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.subject_edit = QtGui.QLineEdit(self.tab)
        self.subject_edit.setObjectName(_fromUtf8("subject_edit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.subject_edit)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.paradigm_combo = QtGui.QComboBox(self.tab)
        self.paradigm_combo.setObjectName(_fromUtf8("paradigm_combo"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.paradigm_combo)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.contrast_combo = QtGui.QComboBox(self.tab)
        self.contrast_combo.setObjectName(_fromUtf8("contrast_combo"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.contrast_combo)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtGui.QFormLayout.LabelRole, spacerItem)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.slice_spin = QtGui.QSpinBox(self.tab)
        self.slice_spin.setObjectName(_fromUtf8("slice_spin"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.slice_spin)
        self.image_orientation_combo = QtGui.QComboBox(self.tab)
        self.image_orientation_combo.setObjectName(_fromUtf8("image_orientation_combo"))
        self.image_orientation_combo.addItem(_fromUtf8(""))
        self.image_orientation_combo.addItem(_fromUtf8(""))
        self.image_orientation_combo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.image_orientation_combo)
        self.show_contours_check = QtGui.QCheckBox(self.tab)
        self.show_contours_check.setChecked(True)
        self.show_contours_check.setObjectName(_fromUtf8("show_contours_check"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.show_contours_check)
        self.slice_slider = QtGui.QSlider(self.tab)
        self.slice_slider.setOrientation(QtCore.Qt.Horizontal)
        self.slice_slider.setObjectName(_fromUtf8("slice_slider"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.slice_slider)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtGui.QFormLayout.LabelRole, spacerItem1)
        self.show_contours_value = QtGui.QDoubleSpinBox(self.tab)
        self.show_contours_value.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        self.show_contours_value.setDecimals(3)
        self.show_contours_value.setMinimum(0.0)
        self.show_contours_value.setSingleStep(0.1)
        self.show_contours_value.setProperty("value", 5.0)
        self.show_contours_value.setObjectName(_fromUtf8("show_contours_value"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.show_contours_value)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_8)
        self.contour_opacity_slider = QtGui.QSlider(self.tab)
        self.contour_opacity_slider.setMaximum(100)
        self.contour_opacity_slider.setProperty("value", 100)
        self.contour_opacity_slider.setTracking(False)
        self.contour_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.contour_opacity_slider.setObjectName(_fromUtf8("contour_opacity_slider"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.contour_opacity_slider)
        self.fMRI.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.frozen_points_table = QtGui.QTableView(self.tab_2)
        self.frozen_points_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.frozen_points_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.frozen_points_table.setObjectName(_fromUtf8("frozen_points_table"))
        self.frozen_points_table.horizontalHeader().setStretchLastSection(True)
        self.frozen_points_table.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.frozen_points_table)
        self.frame = QtGui.QFrame(self.tab_2)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.freeze_point_button = QtGui.QPushButton(self.frame)
        self.freeze_point_button.setObjectName(_fromUtf8("freeze_point_button"))
        self.gridLayout_2.addWidget(self.freeze_point_button, 0, 0, 1, 1)
        self.for_all_subjects = QtGui.QPushButton(self.frame)
        self.for_all_subjects.setObjectName(_fromUtf8("for_all_subjects"))
        self.gridLayout_2.addWidget(self.for_all_subjects, 0, 1, 1, 1)
        self.time_color_combo = QtGui.QComboBox(self.frame)
        self.time_color_combo.setObjectName(_fromUtf8("time_color_combo"))
        self.time_color_combo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.time_color_combo, 1, 0, 1, 1)
        self.time_aggregrate_combo = QtGui.QComboBox(self.frame)
        self.time_aggregrate_combo.setObjectName(_fromUtf8("time_aggregrate_combo"))
        self.time_aggregrate_combo.addItem(_fromUtf8(""))
        self.time_aggregrate_combo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.time_aggregrate_combo, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.clear_button = QtGui.QPushButton(self.tab_2)
        self.clear_button.setObjectName(_fromUtf8("clear_button"))
        self.verticalLayout_2.addWidget(self.clear_button)
        self.progressBar = QtGui.QProgressBar(self.tab_2)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_2.addWidget(self.progressBar)
        self.fMRI.addTab(self.tab_2, _fromUtf8(""))
        self.vtk_frame = QtGui.QFrame(self.splitter)
        self.vtk_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.vtk_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.vtk_frame.setObjectName(_fromUtf8("vtk_frame"))
        self.timeline_frame = QtGui.QFrame(self.splitter_2)
        self.timeline_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.timeline_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.timeline_frame.setObjectName(_fromUtf8("timeline_frame"))
        self.verticalLayout.addWidget(self.splitter_2)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        fMRI_Explorer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fMRI_Explorer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuAccept_Samples = QtGui.QMenu(self.menuFile)
        self.menuAccept_Samples.setObjectName(_fromUtf8("menuAccept_Samples"))
        fMRI_Explorer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(fMRI_Explorer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        fMRI_Explorer.setStatusBar(self.statusbar)
        self.actionSave_scenario = QtGui.QAction(fMRI_Explorer)
        self.actionSave_scenario.setObjectName(_fromUtf8("actionSave_scenario"))
        self.actionLoad_scenario = QtGui.QAction(fMRI_Explorer)
        self.actionLoad_scenario.setObjectName(_fromUtf8("actionLoad_scenario"))
        self.actionGraph = QtGui.QAction(fMRI_Explorer)
        self.actionGraph.setObjectName(_fromUtf8("actionGraph"))
        self.actionSignals = QtGui.QAction(fMRI_Explorer)
        self.actionSignals.setObjectName(_fromUtf8("actionSignals"))
        self.actionSelect_Sample = QtGui.QAction(fMRI_Explorer)
        self.actionSelect_Sample.setObjectName(_fromUtf8("actionSelect_Sample"))
        self.actionFrozen_Table = QtGui.QAction(fMRI_Explorer)
        self.actionFrozen_Table.setObjectName(_fromUtf8("actionFrozen_Table"))
        self.actionSda = QtGui.QAction(fMRI_Explorer)
        self.actionSda.setObjectName(_fromUtf8("actionSda"))
        self.menuExport.addAction(self.actionGraph)
        self.menuExport.addAction(self.actionSignals)
        self.menuExport.addAction(self.actionFrozen_Table)
        self.menuFile.addAction(self.actionSave_scenario)
        self.menuFile.addAction(self.actionLoad_scenario)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSelect_Sample)
        self.menuFile.addAction(self.menuAccept_Samples.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(fMRI_Explorer)
        self.fMRI.setCurrentIndex(0)
        QtCore.QObject.connect(self.slice_spin, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slice_slider.setValue)
        QtCore.QObject.connect(self.slice_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slice_spin.setValue)
        QtCore.QMetaObject.connectSlotsByName(fMRI_Explorer)

    def retranslateUi(self, fMRI_Explorer):
        fMRI_Explorer.setWindowTitle(_translate("fMRI_Explorer", "Braviz - fMRI Explore", None))
        self.label.setText(_translate("fMRI_Explorer", "Subject:", None))
        self.subject_edit.setText(_translate("fMRI_Explorer", "93", None))
        self.label_2.setText(_translate("fMRI_Explorer", "Paradigm:", None))
        self.label_3.setText(_translate("fMRI_Explorer", "Contrast:", None))
        self.label_4.setText(_translate("fMRI_Explorer", "Image Orientation:", None))
        self.label_5.setText(_translate("fMRI_Explorer", "Image Slice:", None))
        self.image_orientation_combo.setItemText(0, _translate("fMRI_Explorer", "Axial", None))
        self.image_orientation_combo.setItemText(1, _translate("fMRI_Explorer", "Coronal", None))
        self.image_orientation_combo.setItemText(2, _translate("fMRI_Explorer", "Sagital", None))
        self.show_contours_check.setText(_translate("fMRI_Explorer", "Show contours", None))
        self.label_8.setText(_translate("fMRI_Explorer", "Opacity:", None))
        self.fMRI.setTabText(self.fMRI.indexOf(self.tab), _translate("fMRI_Explorer", "fMRI", None))
        self.label_6.setText(_translate("fMRI_Explorer", "Frozen points:", None))
        self.freeze_point_button.setText(_translate("fMRI_Explorer", "Freeze current point", None))
        self.for_all_subjects.setText(_translate("fMRI_Explorer", "Get point for All Subjects", None))
        self.time_color_combo.setItemText(0, _translate("fMRI_Explorer", "Same color", None))
        self.time_aggregrate_combo.setItemText(0, _translate("fMRI_Explorer", "Individual lines", None))
        self.time_aggregrate_combo.setItemText(1, _translate("fMRI_Explorer", "Aggregrate", None))
        self.clear_button.setText(_translate("fMRI_Explorer", "Clear", None))
        self.fMRI.setTabText(self.fMRI.indexOf(self.tab_2), _translate("fMRI_Explorer", "Timeline", None))
        self.menuFile.setTitle(_translate("fMRI_Explorer", "File", None))
        self.menuExport.setTitle(_translate("fMRI_Explorer", "Export", None))
        self.menuAccept_Samples.setTitle(_translate("fMRI_Explorer", "Accept Samples", None))
        self.actionSave_scenario.setText(_translate("fMRI_Explorer", "Save scenario", None))
        self.actionLoad_scenario.setText(_translate("fMRI_Explorer", "Load scenario", None))
        self.actionGraph.setText(_translate("fMRI_Explorer", "Graph", None))
        self.actionSignals.setText(_translate("fMRI_Explorer", "Signals", None))
        self.actionSelect_Sample.setText(_translate("fMRI_Explorer", "Select Sample", None))
        self.actionFrozen_Table.setText(_translate("fMRI_Explorer", "Frozen Table", None))
        self.actionSda.setText(_translate("fMRI_Explorer", "sda", None))

import resources_rc
