# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\linear_reg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LinearModel(object):
    def setupUi(self, LinearModel):
        LinearModel.setObjectName(_fromUtf8("LinearModel"))
        LinearModel.resize(899, 661)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/linear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LinearModel.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(LinearModel)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.control_widget = QtGui.QFrame(self.centralwidget)
        self.control_widget.setMaximumSize(QtCore.QSize(309, 16777215))
        self.control_widget.setFrameShape(QtGui.QFrame.NoFrame)
        self.control_widget.setFrameShadow(QtGui.QFrame.Raised)
        self.control_widget.setObjectName(_fromUtf8("control_widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.control_widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.control_widget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setMaximumSize(QtCore.QSize(56, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.outcome_sel = QtGui.QComboBox(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outcome_sel.sizePolicy().hasHeightForWidth())
        self.outcome_sel.setSizePolicy(sizePolicy)
        self.outcome_sel.setObjectName(_fromUtf8("outcome_sel"))
        self.outcome_sel.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.outcome_sel)
        self.outcome_type = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outcome_type.sizePolicy().hasHeightForWidth())
        self.outcome_type.setSizePolicy(sizePolicy)
        self.outcome_type.setMinimumSize(QtCore.QSize(69, 0))
        self.outcome_type.setStyleSheet(_fromUtf8("background-color:rgb(149, 149, 149)\n"
""))
        self.outcome_type.setFrameShape(QtGui.QFrame.StyledPanel)
        self.outcome_type.setScaledContents(False)
        self.outcome_type.setAlignment(QtCore.Qt.AlignCenter)
        self.outcome_type.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.outcome_type.setObjectName(_fromUtf8("outcome_type"))
        self.horizontalLayout_2.addWidget(self.outcome_type)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.reg_table = QtGui.QTableView(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.reg_table.sizePolicy().hasHeightForWidth())
        self.reg_table.setSizePolicy(sizePolicy)
        self.reg_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.reg_table.setAlternatingRowColors(True)
        self.reg_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.reg_table.setObjectName(_fromUtf8("reg_table"))
        self.reg_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.reg_table)
        self.frame_5 = QtGui.QFrame(self.frame)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.add_regressor_button = QtGui.QPushButton(self.frame_5)
        self.add_regressor_button.setObjectName(_fromUtf8("add_regressor_button"))
        self.horizontalLayout_3.addWidget(self.add_regressor_button)
        self.add_interaction_button = QtGui.QPushButton(self.frame_5)
        self.add_interaction_button.setObjectName(_fromUtf8("add_interaction_button"))
        self.horizontalLayout_3.addWidget(self.add_interaction_button)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.missing_label = QtGui.QLabel(self.frame)
        self.missing_label.setObjectName(_fromUtf8("missing_label"))
        self.verticalLayout_3.addWidget(self.missing_label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_4 = QtGui.QFrame(self.control_widget)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.frame_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.sample_tree = QtGui.QTreeView(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_tree.sizePolicy().hasHeightForWidth())
        self.sample_tree.setSizePolicy(sizePolicy)
        self.sample_tree.setMaximumSize(QtCore.QSize(16777215, 200))
        self.sample_tree.setAlternatingRowColors(True)
        self.sample_tree.setUniformRowHeights(True)
        self.sample_tree.setObjectName(_fromUtf8("sample_tree"))
        self.verticalLayout_4.addWidget(self.sample_tree)
        self.modify_sample_button = QtGui.QPushButton(self.frame_4)
        self.modify_sample_button.setEnabled(False)
        self.modify_sample_button.setObjectName(_fromUtf8("modify_sample_button"))
        self.verticalLayout_4.addWidget(self.modify_sample_button)
        self.calculate_button = QtGui.QPushButton(self.frame_4)
        self.calculate_button.setEnabled(False)
        self.calculate_button.setObjectName(_fromUtf8("calculate_button"))
        self.verticalLayout_4.addWidget(self.calculate_button)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout_4.addWidget(self.control_widget)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.plot_frame = QtGui.QFrame(self.frame_2)
        self.plot_frame.setMinimumSize(QtCore.QSize(0, 258))
        self.plot_frame.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.plot_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.plot_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_frame.setObjectName(_fromUtf8("plot_frame"))
        self.verticalLayout_2.addWidget(self.plot_frame)
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.results_table = QtGui.QTableView(self.frame_2)
        self.results_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.results_table.setDragEnabled(True)
        self.results_table.setAlternatingRowColors(True)
        self.results_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.results_table.setSortingEnabled(True)
        self.results_table.setObjectName(_fromUtf8("results_table"))
        self.results_table.horizontalHeader().setStretchLastSection(True)
        self.results_table.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.results_table)
        self.parameters_layout = QtGui.QFrame(self.frame_2)
        self.parameters_layout.setFrameShape(QtGui.QFrame.NoFrame)
        self.parameters_layout.setFrameShadow(QtGui.QFrame.Raised)
        self.parameters_layout.setObjectName(_fromUtf8("parameters_layout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.parameters_layout)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.r_squared_label = QtGui.QLabel(self.parameters_layout)
        self.r_squared_label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.r_squared_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.r_squared_label.setObjectName(_fromUtf8("r_squared_label"))
        self.horizontalLayout_5.addWidget(self.r_squared_label)
        self.f_value_label = QtGui.QLabel(self.parameters_layout)
        self.f_value_label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.f_value_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.f_value_label.setObjectName(_fromUtf8("f_value_label"))
        self.horizontalLayout_5.addWidget(self.f_value_label)
        self.p_value_label = QtGui.QLabel(self.parameters_layout)
        self.p_value_label.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.p_value_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.p_value_label.setObjectName(_fromUtf8("p_value_label"))
        self.horizontalLayout_5.addWidget(self.p_value_label)
        self.verticalLayout_2.addWidget(self.parameters_layout)
        self.frame_6 = QtGui.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.factor_plot_button = QtGui.QPushButton(self.frame_6)
        self.factor_plot_button.setObjectName(_fromUtf8("factor_plot_button"))
        self.horizontalLayout.addWidget(self.factor_plot_button)
        self.residuals_plot_button = QtGui.QPushButton(self.frame_6)
        self.residuals_plot_button.setObjectName(_fromUtf8("residuals_plot_button"))
        self.horizontalLayout.addWidget(self.residuals_plot_button)
        self.verticalLayout_2.addWidget(self.frame_6)
        self.verticalLayout_2.setStretch(0, 1)
        self.horizontalLayout_4.addWidget(self.frame_2)
        LinearModel.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(LinearModel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuAccept_samples = QtGui.QMenu(self.menuFile)
        self.menuAccept_samples.setObjectName(_fromUtf8("menuAccept_samples"))
        LinearModel.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(LinearModel)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        LinearModel.setStatusBar(self.statusbar)
        self.actionSave_scneario = QtGui.QAction(LinearModel)
        self.actionSave_scneario.setObjectName(_fromUtf8("actionSave_scneario"))
        self.actionLoad_scenario = QtGui.QAction(LinearModel)
        self.actionLoad_scenario.setObjectName(_fromUtf8("actionLoad_scenario"))
        self.actionImages = QtGui.QAction(LinearModel)
        self.actionImages.setObjectName(_fromUtf8("actionImages"))
        self.actionData = QtGui.QAction(LinearModel)
        self.actionData.setObjectName(_fromUtf8("actionData"))
        self.actionLoad_sample = QtGui.QAction(LinearModel)
        self.actionLoad_sample.setObjectName(_fromUtf8("actionLoad_sample"))
        self.actionSend_sample = QtGui.QAction(LinearModel)
        self.actionSend_sample.setObjectName(_fromUtf8("actionSend_sample"))
        self.actionModify_sample = QtGui.QAction(LinearModel)
        self.actionModify_sample.setObjectName(_fromUtf8("actionModify_sample"))
        self.menuExport.addAction(self.actionImages)
        self.menuExport.addAction(self.actionData)
        self.menuFile.addAction(self.actionSave_scneario)
        self.menuFile.addAction(self.actionLoad_scenario)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_sample)
        self.menuFile.addAction(self.actionModify_sample)
        self.menuFile.addAction(self.actionSend_sample)
        self.menuFile.addAction(self.menuAccept_samples.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.label.setBuddy(self.outcome_sel)
        self.label_2.setBuddy(self.reg_table)
        self.label_3.setBuddy(self.sample_tree)

        self.retranslateUi(LinearModel)
        self.outcome_sel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LinearModel)

    def retranslateUi(self, LinearModel):
        LinearModel.setWindowTitle(_translate("LinearModel", "Braviz - Linear Model", None))
        self.label.setToolTip(_translate("LinearModel", "Dependent Variable", None))
        self.label.setText(_translate("LinearModel", "&Outcome: ", None))
        self.outcome_sel.setItemText(0, _translate("LinearModel", "Select Outcome...", None))
        self.outcome_type.setToolTip(_translate("LinearModel", "Data type of outcome", None))
        self.outcome_type.setWhatsThis(_translate("LinearModel", "The outcome may be an ordinal, binary or nominal variable", None))
        self.outcome_type.setText(_translate("LinearModel", "Type", None))
        self.label_2.setToolTip(_translate("LinearModel", "Independent Variables", None))
        self.label_2.setText(_translate("LinearModel", "Regressors", None))
        self.add_regressor_button.setToolTip(_translate("LinearModel", "Add regressor variables for the anova analysis", None))
        self.add_regressor_button.setText(_translate("LinearModel", "Add Regresor", None))
        self.add_interaction_button.setToolTip(_translate("LinearModel", "Add interaction terms to this anova analysis", None))
        self.add_interaction_button.setText(_translate("LinearModel", "Add Interaction", None))
        self.missing_label.setText(_translate("LinearModel", "Missing Values:", None))
        self.label_3.setText(_translate("LinearModel", "&Sample", None))
        self.modify_sample_button.setToolTip(_translate("LinearModel", "Change the datapoints that will be used in this anova analysis", None))
        self.modify_sample_button.setText(_translate("LinearModel", "Load sample", None))
        self.calculate_button.setToolTip(_translate("LinearModel", "Fit the linear model", None))
        self.calculate_button.setText(_translate("LinearModel", "Calculate Linear Regression", None))
        self.label_7.setText(_translate("LinearModel", "Coefficients:", None))
        self.r_squared_label.setText(_translate("LinearModel", "R<sup>2</sup> = ", None))
        self.f_value_label.setText(_translate("LinearModel", "F =", None))
        self.p_value_label.setText(_translate("LinearModel", "P =", None))
        self.factor_plot_button.setText(_translate("LinearModel", "Factor Plot", None))
        self.residuals_plot_button.setText(_translate("LinearModel", "Residuals Plot", None))
        self.menuFile.setTitle(_translate("LinearModel", "&File", None))
        self.menuExport.setTitle(_translate("LinearModel", "Export", None))
        self.menuAccept_samples.setTitle(_translate("LinearModel", "Accept samples", None))
        self.actionSave_scneario.setText(_translate("LinearModel", "Save scenario", None))
        self.actionLoad_scenario.setText(_translate("LinearModel", "Load scenario", None))
        self.actionImages.setText(_translate("LinearModel", "Images", None))
        self.actionData.setText(_translate("LinearModel", "Data", None))
        self.actionLoad_sample.setText(_translate("LinearModel", "Load sample", None))
        self.actionSend_sample.setText(_translate("LinearModel", "Send sample", None))
        self.actionModify_sample.setText(_translate("LinearModel", "Modify sample", None))

import resources_rc
