# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\logic_bundles.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LogicBundlesApp(object):
    def setupUi(self, LogicBundlesApp):
        LogicBundlesApp.setObjectName(_fromUtf8("LogicBundlesApp"))
        LogicBundlesApp.resize(1211, 745)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/logic.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        LogicBundlesApp.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(LogicBundlesApp)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.ContextTab = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ContextTab.sizePolicy().hasHeightForWidth())
        self.ContextTab.setSizePolicy(sizePolicy)
        self.ContextTab.setObjectName(_fromUtf8("ContextTab"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.treeView = QtGui.QTreeView(self.tab)
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setProperty("showDropIndicator", False)
        self.treeView.setDragDropMode(QtGui.QAbstractItemView.NoDragDrop)
        self.treeView.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setAnimated(True)
        self.treeView.setWordWrap(True)
        self.treeView.setHeaderHidden(True)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout_3.addWidget(self.treeView)
        self.add_logic = QtGui.QPushButton(self.tab)
        self.add_logic.setObjectName(_fromUtf8("add_logic"))
        self.verticalLayout_3.addWidget(self.add_logic)
        self.add_segmented = QtGui.QPushButton(self.tab)
        self.add_segmented.setObjectName(_fromUtf8("add_segmented"))
        self.verticalLayout_3.addWidget(self.add_segmented)
        self.add_roi = QtGui.QPushButton(self.tab)
        self.add_roi.setObjectName(_fromUtf8("add_roi"))
        self.verticalLayout_3.addWidget(self.add_roi)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.waypoints_opacity = QtGui.QSlider(self.tab)
        self.waypoints_opacity.setMaximum(100)
        self.waypoints_opacity.setProperty("value", 100)
        self.waypoints_opacity.setOrientation(QtCore.Qt.Horizontal)
        self.waypoints_opacity.setObjectName(_fromUtf8("waypoints_opacity"))
        self.verticalLayout_3.addWidget(self.waypoints_opacity)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout = QtGui.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fiber_scalar_combo = QtGui.QComboBox(self.frame_3)
        self.fiber_scalar_combo.setEnabled(True)
        self.fiber_scalar_combo.setObjectName(_fromUtf8("fiber_scalar_combo"))
        self.fiber_scalar_combo.addItem(_fromUtf8(""))
        self.fiber_scalar_combo.addItem(_fromUtf8(""))
        self.fiber_scalar_combo.addItem(_fromUtf8(""))
        self.fiber_scalar_combo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.fiber_scalar_combo, 2, 0, 1, 1)
        self.preview_bundle = QtGui.QCheckBox(self.frame_3)
        self.preview_bundle.setObjectName(_fromUtf8("preview_bundle"))
        self.gridLayout.addWidget(self.preview_bundle, 1, 0, 1, 2)
        self.export_to_db = QtGui.QPushButton(self.frame_3)
        self.export_to_db.setEnabled(False)
        self.export_to_db.setObjectName(_fromUtf8("export_to_db"))
        self.gridLayout.addWidget(self.export_to_db, 3, 0, 1, 2)
        self.scalar_box = QtGui.QLineEdit(self.frame_3)
        self.scalar_box.setReadOnly(True)
        self.scalar_box.setObjectName(_fromUtf8("scalar_box"))
        self.gridLayout.addWidget(self.scalar_box, 2, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_3.setStretch(1, 1)
        self.ContextTab.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayout = QtGui.QFormLayout(self.tab_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.image_combo = QtGui.QComboBox(self.tab_2)
        self.image_combo.setObjectName(_fromUtf8("image_combo"))
        self.image_combo.addItem(_fromUtf8(""))
        self.image_combo.addItem(_fromUtf8(""))
        self.image_combo.addItem(_fromUtf8(""))
        self.image_combo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.image_combo)
        self.axial_check = QtGui.QCheckBox(self.tab_2)
        self.axial_check.setChecked(True)
        self.axial_check.setObjectName(_fromUtf8("axial_check"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.axial_check)
        self.coronal_check = QtGui.QCheckBox(self.tab_2)
        self.coronal_check.setChecked(False)
        self.coronal_check.setObjectName(_fromUtf8("coronal_check"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.coronal_check)
        self.sagital_check = QtGui.QCheckBox(self.tab_2)
        self.sagital_check.setChecked(False)
        self.sagital_check.setObjectName(_fromUtf8("sagital_check"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.sagital_check)
        self.axial_slice = QtGui.QSpinBox(self.tab_2)
        self.axial_slice.setObjectName(_fromUtf8("axial_slice"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.axial_slice)
        self.coronal_slice = QtGui.QSpinBox(self.tab_2)
        self.coronal_slice.setObjectName(_fromUtf8("coronal_slice"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.coronal_slice)
        self.sagital_slice = QtGui.QSpinBox(self.tab_2)
        self.sagital_slice.setObjectName(_fromUtf8("sagital_slice"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.sagital_slice)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.line_3)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_13)
        self.surface_combo = QtGui.QComboBox(self.tab_2)
        self.surface_combo.setObjectName(_fromUtf8("surface_combo"))
        self.surface_combo.addItem(_fromUtf8(""))
        self.surface_combo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.surface_combo)
        self.left_cortex_check = QtGui.QCheckBox(self.tab_2)
        self.left_cortex_check.setObjectName(_fromUtf8("left_cortex_check"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.left_cortex_check)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_14)
        self.scalar_combo = QtGui.QComboBox(self.tab_2)
        self.scalar_combo.setObjectName(_fromUtf8("scalar_combo"))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.scalar_combo)
        self.right_cortex_check = QtGui.QCheckBox(self.tab_2)
        self.right_cortex_check.setObjectName(_fromUtf8("right_cortex_check"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.right_cortex_check)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.SpanningRole, self.label_16)
        self.cortex_opac = QtGui.QSlider(self.tab_2)
        self.cortex_opac.setMaximum(100)
        self.cortex_opac.setProperty("value", 100)
        self.cortex_opac.setTracking(False)
        self.cortex_opac.setOrientation(QtCore.Qt.Horizontal)
        self.cortex_opac.setObjectName(_fromUtf8("cortex_opac"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.SpanningRole, self.cortex_opac)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.label_4)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(14, QtGui.QFormLayout.LabelRole, spacerItem2)
        self.space_combo = QtGui.QComboBox(self.tab_2)
        self.space_combo.setObjectName(_fromUtf8("space_combo"))
        self.space_combo.addItem(_fromUtf8(""))
        self.space_combo.addItem(_fromUtf8(""))
        self.space_combo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.space_combo)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.contrast_combo = QtGui.QComboBox(self.tab_2)
        self.contrast_combo.setObjectName(_fromUtf8("contrast_combo"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.contrast_combo)
        self.ContextTab.addTab(self.tab_2, _fromUtf8(""))
        self.frame = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(600, 0))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.vtk_frame = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_frame.sizePolicy().hasHeightForWidth())
        self.vtk_frame.setSizePolicy(sizePolicy)
        self.vtk_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.vtk_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.vtk_frame.setObjectName(_fromUtf8("vtk_frame"))
        self.verticalLayout_2.addWidget(self.vtk_frame)
        self.frame_2 = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout.addWidget(self.label_15)
        self.subjects_list = QtGui.QListView(self.frame_2)
        self.subjects_list.setAlternatingRowColors(True)
        self.subjects_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.subjects_list.setObjectName(_fromUtf8("subjects_list"))
        self.verticalLayout.addWidget(self.subjects_list)
        self.horizontalLayout.addWidget(self.splitter)
        LogicBundlesApp.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(LogicBundlesApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1211, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        LogicBundlesApp.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(LogicBundlesApp)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        LogicBundlesApp.setStatusBar(self.statusbar)
        self.actionSave_Scenario = QtGui.QAction(LogicBundlesApp)
        self.actionSave_Scenario.setObjectName(_fromUtf8("actionSave_Scenario"))
        self.actionLoad_Scenario = QtGui.QAction(LogicBundlesApp)
        self.actionLoad_Scenario.setObjectName(_fromUtf8("actionLoad_Scenario"))
        self.actionSave_Bundle = QtGui.QAction(LogicBundlesApp)
        self.actionSave_Bundle.setObjectName(_fromUtf8("actionSave_Bundle"))
        self.actionLoad_Bundle = QtGui.QAction(LogicBundlesApp)
        self.actionLoad_Bundle.setObjectName(_fromUtf8("actionLoad_Bundle"))
        self.menuFile.addAction(self.actionSave_Scenario)
        self.menuFile.addAction(self.actionLoad_Scenario)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Bundle)
        self.menuFile.addAction(self.actionLoad_Bundle)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(LogicBundlesApp)
        self.ContextTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LogicBundlesApp)

    def retranslateUi(self, LogicBundlesApp):
        LogicBundlesApp.setWindowTitle(_translate("LogicBundlesApp", "Braviz Logic Bundles", None))
        self.label_3.setText(_translate("LogicBundlesApp", "Waypoints", None))
        self.add_logic.setText(_translate("LogicBundlesApp", "Add Logic Node", None))
        self.add_segmented.setText(_translate("LogicBundlesApp", "Add Segmented Structure", None))
        self.add_roi.setText(_translate("LogicBundlesApp", "Add ROI", None))
        self.label_5.setText(_translate("LogicBundlesApp", "Waypoints Opacity", None))
        self.fiber_scalar_combo.setItemText(0, _translate("LogicBundlesApp", "Count", None))
        self.fiber_scalar_combo.setItemText(1, _translate("LogicBundlesApp", "Mean Length", None))
        self.fiber_scalar_combo.setItemText(2, _translate("LogicBundlesApp", "Mean FA", None))
        self.fiber_scalar_combo.setItemText(3, _translate("LogicBundlesApp", "Mean DC", None))
        self.preview_bundle.setText(_translate("LogicBundlesApp", "Preview Bundle", None))
        self.export_to_db.setText(_translate("LogicBundlesApp", "Export to DB", None))
        self.ContextTab.setTabText(self.ContextTab.indexOf(self.tab), _translate("LogicBundlesApp", "Bundle", None))
        self.label.setText(_translate("LogicBundlesApp", "Image: ", None))
        self.image_combo.setItemText(0, _translate("LogicBundlesApp", "MRI", None))
        self.image_combo.setItemText(1, _translate("LogicBundlesApp", "APARC", None))
        self.image_combo.setItemText(2, _translate("LogicBundlesApp", "WMPARC", None))
        self.image_combo.setItemText(3, _translate("LogicBundlesApp", "DTI", None))
        self.axial_check.setText(_translate("LogicBundlesApp", "Axial", None))
        self.coronal_check.setText(_translate("LogicBundlesApp", "Coronal", None))
        self.sagital_check.setText(_translate("LogicBundlesApp", "Sagital", None))
        self.label_2.setText(_translate("LogicBundlesApp", "Slice:", None))
        self.label_13.setText(_translate("LogicBundlesApp", "Cortex:", None))
        self.surface_combo.setItemText(0, _translate("LogicBundlesApp", "Pial", None))
        self.surface_combo.setItemText(1, _translate("LogicBundlesApp", "White", None))
        self.left_cortex_check.setText(_translate("LogicBundlesApp", "Left", None))
        self.label_14.setText(_translate("LogicBundlesApp", "Scalars:", None))
        self.scalar_combo.setItemText(0, _translate("LogicBundlesApp", "Curv", None))
        self.scalar_combo.setItemText(1, _translate("LogicBundlesApp", "Average  curv.", None))
        self.scalar_combo.setItemText(2, _translate("LogicBundlesApp", "Area", None))
        self.scalar_combo.setItemText(3, _translate("LogicBundlesApp", "Thickness", None))
        self.scalar_combo.setItemText(4, _translate("LogicBundlesApp", "Sulc", None))
        self.scalar_combo.setItemText(5, _translate("LogicBundlesApp", "Parcellation", None))
        self.scalar_combo.setItemText(6, _translate("LogicBundlesApp", "Parcellation 2009", None))
        self.scalar_combo.setItemText(7, _translate("LogicBundlesApp", "Parcellation DKT", None))
        self.scalar_combo.setItemText(8, _translate("LogicBundlesApp", "Broadman Area", None))
        self.right_cortex_check.setText(_translate("LogicBundlesApp", "Right", None))
        self.label_16.setText(_translate("LogicBundlesApp", "Opacity", None))
        self.label_4.setText(_translate("LogicBundlesApp", "Coordinates:", None))
        self.space_combo.setItemText(0, _translate("LogicBundlesApp", "Subject", None))
        self.space_combo.setItemText(1, _translate("LogicBundlesApp", "Talairach", None))
        self.space_combo.setItemText(2, _translate("LogicBundlesApp", "Dartel", None))
        self.label_6.setText(_translate("LogicBundlesApp", "Contrast:", None))
        self.ContextTab.setTabText(self.ContextTab.indexOf(self.tab_2), _translate("LogicBundlesApp", "Context", None))
        self.label_15.setText(_translate("LogicBundlesApp", "Subjects", None))
        self.menuFile.setTitle(_translate("LogicBundlesApp", "File", None))
        self.actionSave_Scenario.setText(_translate("LogicBundlesApp", "Save Scenario", None))
        self.actionLoad_Scenario.setText(_translate("LogicBundlesApp", "Load Scenario", None))
        self.actionSave_Bundle.setText(_translate("LogicBundlesApp", "Save Bundle", None))
        self.actionLoad_Bundle.setText(_translate("LogicBundlesApp", "Load Bundle", None))

import resources_rc
