# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\menu2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BavizMenu(object):
    def setupUi(self, BavizMenu):
        BavizMenu.setObjectName(_fromUtf8("BavizMenu"))
        BavizMenu.resize(800, 750)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BavizMenu.sizePolicy().hasHeightForWidth())
        BavizMenu.setSizePolicy(sizePolicy)
        BavizMenu.setStyleSheet(_fromUtf8("QWidget#centralwidget{\n"
"background-image: url(:/icons/imagine.svg);\n"
"background-repeat: no-repeat;\n"
"background-position: bottom right;\n"
"background-origin: content;\n"
"}"))
        BavizMenu.setIconSize(QtCore.QSize(100, 100))
        BavizMenu.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtGui.QWidget(BavizMenu)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.frame_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.subject_overview = QtGui.QToolButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/some_fibers.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.subject_overview.setIcon(icon)
        self.subject_overview.setIconSize(QtCore.QSize(120, 120))
        self.subject_overview.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.subject_overview.setObjectName(_fromUtf8("subject_overview"))
        self.horizontalLayout.addWidget(self.subject_overview)
        self.toolButton_13 = QtGui.QToolButton(self.groupBox)
        self.toolButton_13.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/amygdala_spharm.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_13.setIcon(icon1)
        self.toolButton_13.setIconSize(QtCore.QSize(120, 120))
        self.toolButton_13.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_13.setObjectName(_fromUtf8("toolButton_13"))
        self.horizontalLayout.addWidget(self.toolButton_13)
        self.toolButton_14 = QtGui.QToolButton(self.groupBox)
        self.toolButton_14.setEnabled(False)
        self.toolButton_14.setIcon(icon1)
        self.toolButton_14.setIconSize(QtCore.QSize(120, 120))
        self.toolButton_14.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_14.setObjectName(_fromUtf8("toolButton_14"))
        self.horizontalLayout.addWidget(self.toolButton_14)
        self.toolButton_15 = QtGui.QToolButton(self.groupBox)
        self.toolButton_15.setEnabled(False)
        self.toolButton_15.setIcon(icon1)
        self.toolButton_15.setIconSize(QtCore.QSize(120, 120))
        self.toolButton_15.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_15.setObjectName(_fromUtf8("toolButton_15"))
        self.horizontalLayout.addWidget(self.toolButton_15)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.sample_overview = QtGui.QToolButton(self.groupBox_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/sample_overview.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.sample_overview.setIcon(icon2)
        self.sample_overview.setIconSize(QtCore.QSize(120, 120))
        self.sample_overview.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.sample_overview.setObjectName(_fromUtf8("sample_overview"))
        self.horizontalLayout_2.addWidget(self.sample_overview)
        self.toolButton_11 = QtGui.QToolButton(self.groupBox_2)
        self.toolButton_11.setEnabled(False)
        self.toolButton_11.setIcon(icon1)
        self.toolButton_11.setIconSize(QtCore.QSize(120, 120))
        self.toolButton_11.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_11.setObjectName(_fromUtf8("toolButton_11"))
        self.horizontalLayout_2.addWidget(self.toolButton_11)
        self.toolButton_10 = QtGui.QToolButton(self.groupBox_2)
        self.toolButton_10.setEnabled(False)
        self.toolButton_10.setIcon(icon1)
        self.toolButton_10.setIconSize(QtCore.QSize(120, 120))
        self.toolButton_10.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_10.setObjectName(_fromUtf8("toolButton_10"))
        self.horizontalLayout_2.addWidget(self.toolButton_10)
        self.toolButton_12 = QtGui.QToolButton(self.groupBox_2)
        self.toolButton_12.setEnabled(False)
        self.toolButton_12.setIcon(icon1)
        self.toolButton_12.setIconSize(QtCore.QSize(120, 120))
        self.toolButton_12.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_12.setObjectName(_fromUtf8("toolButton_12"))
        self.horizontalLayout_2.addWidget(self.toolButton_12)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.anova = QtGui.QToolButton(self.groupBox_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/baviz_anova.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.anova.setIcon(icon3)
        self.anova.setIconSize(QtCore.QSize(120, 120))
        self.anova.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.anova.setObjectName(_fromUtf8("anova"))
        self.horizontalLayout_3.addWidget(self.anova)
        self.correlations = QtGui.QToolButton(self.groupBox_3)
        self.correlations.setEnabled(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/correlations_app.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.correlations.setIcon(icon4)
        self.correlations.setIconSize(QtCore.QSize(120, 120))
        self.correlations.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.correlations.setObjectName(_fromUtf8("correlations"))
        self.horizontalLayout_3.addWidget(self.correlations)
        self.linear_model = QtGui.QToolButton(self.groupBox_3)
        self.linear_model.setEnabled(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/linear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.linear_model.setIcon(icon5)
        self.linear_model.setIconSize(QtCore.QSize(120, 120))
        self.linear_model.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.linear_model.setObjectName(_fromUtf8("linear_model"))
        self.horizontalLayout_3.addWidget(self.linear_model)
        self.toolButton_9 = QtGui.QToolButton(self.groupBox_3)
        self.toolButton_9.setEnabled(False)
        self.toolButton_9.setIcon(icon1)
        self.toolButton_9.setIconSize(QtCore.QSize(120, 120))
        self.toolButton_9.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_9.setObjectName(_fromUtf8("toolButton_9"))
        self.horizontalLayout_3.addWidget(self.toolButton_9)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.variables = QtGui.QToolButton(self.groupBox_4)
        self.variables.setEnabled(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/listview-highlight.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.variables.setIcon(icon6)
        self.variables.setIconSize(QtCore.QSize(50, 30))
        self.variables.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.variables.setObjectName(_fromUtf8("variables"))
        self.horizontalLayout_4.addWidget(self.variables)
        self.scenarios = QtGui.QToolButton(self.groupBox_4)
        self.scenarios.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/gridLayout_aligntop.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.scenarios.setIcon(icon7)
        self.scenarios.setIconSize(QtCore.QSize(50, 30))
        self.scenarios.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.scenarios.setObjectName(_fromUtf8("scenarios"))
        self.horizontalLayout_4.addWidget(self.scenarios)
        self.samples = QtGui.QToolButton(self.groupBox_4)
        self.samples.setEnabled(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/kontact_contacts.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.samples.setIcon(icon8)
        self.samples.setIconSize(QtCore.QSize(50, 30))
        self.samples.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.samples.setObjectName(_fromUtf8("samples"))
        self.horizontalLayout_4.addWidget(self.samples)
        self.users = QtGui.QToolButton(self.groupBox_4)
        self.users.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/metacontact_online.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.users.setIcon(icon9)
        self.users.setIconSize(QtCore.QSize(50, 30))
        self.users.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.users.setObjectName(_fromUtf8("users"))
        self.horizontalLayout_4.addWidget(self.users)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.verticalLayout_2.addWidget(self.frame_2)
        BavizMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(BavizMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        BavizMenu.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(BavizMenu)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BavizMenu.setStatusBar(self.statusbar)

        self.retranslateUi(BavizMenu)
        QtCore.QMetaObject.connectSlotsByName(BavizMenu)

    def retranslateUi(self, BavizMenu):
        BavizMenu.setWindowTitle(_translate("BavizMenu", "MainWindow", None))
        self.groupBox.setTitle(_translate("BavizMenu", "Explore Subjects", None))
        self.subject_overview.setText(_translate("BavizMenu", "Subject Overview", None))
        self.toolButton_13.setText(_translate("BavizMenu", "?", None))
        self.toolButton_14.setText(_translate("BavizMenu", "?", None))
        self.toolButton_15.setText(_translate("BavizMenu", "?", None))
        self.groupBox_2.setTitle(_translate("BavizMenu", "Explore Groups", None))
        self.sample_overview.setText(_translate("BavizMenu", "Sample Overview", None))
        self.toolButton_11.setText(_translate("BavizMenu", "?", None))
        self.toolButton_10.setText(_translate("BavizMenu", "?", None))
        self.toolButton_12.setText(_translate("BavizMenu", "?", None))
        self.groupBox_3.setTitle(_translate("BavizMenu", "Analysis", None))
        self.anova.setText(_translate("BavizMenu", "Anova", None))
        self.correlations.setText(_translate("BavizMenu", "Correlations", None))
        self.linear_model.setText(_translate("BavizMenu", "Linear Model", None))
        self.toolButton_9.setText(_translate("BavizMenu", "?", None))
        self.groupBox_4.setTitle(_translate("BavizMenu", "Manage Data", None))
        self.variables.setText(_translate("BavizMenu", "Variables", None))
        self.scenarios.setText(_translate("BavizMenu", "Scenarios", None))
        self.samples.setText(_translate("BavizMenu", "Samples", None))
        self.users.setText(_translate("BavizMenu", "Users", None))

import resources_rc
