# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\menu_3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BravizMenu(object):
    def setupUi(self, BravizMenu):
        BravizMenu.setObjectName(_fromUtf8("BravizMenu"))
        BravizMenu.resize(941, 811)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/braviz_dianita_small.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BravizMenu.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(BravizMenu)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/braviz_h.png")))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.project_label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.project_label.setFont(font)
        self.project_label.setAlignment(QtCore.Qt.AlignCenter)
        self.project_label.setObjectName(_fromUtf8("project_label"))
        self.horizontalLayout_5.addWidget(self.project_label)
        self.verticalLayout.addWidget(self.frame)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.roi_builder = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roi_builder.sizePolicy().hasHeightForWidth())
        self.roi_builder.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/roi_builder.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.roi_builder.setIcon(icon1)
        self.roi_builder.setIconSize(QtCore.QSize(60, 60))
        self.roi_builder.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.roi_builder.setObjectName(_fromUtf8("roi_builder"))
        self.horizontalLayout.addWidget(self.roi_builder)
        self.logic_bundles = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logic_bundles.sizePolicy().hasHeightForWidth())
        self.logic_bundles.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/logic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logic_bundles.setIcon(icon2)
        self.logic_bundles.setIconSize(QtCore.QSize(60, 60))
        self.logic_bundles.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.logic_bundles.setObjectName(_fromUtf8("logic_bundles"))
        self.horizontalLayout.addWidget(self.logic_bundles)
        self.linear_measure = QtGui.QToolButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linear_measure.sizePolicy().hasHeightForWidth())
        self.linear_measure.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/measure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.linear_measure.setIcon(icon3)
        self.linear_measure.setIconSize(QtCore.QSize(60, 60))
        self.linear_measure.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.linear_measure.setObjectName(_fromUtf8("linear_measure"))
        self.horizontalLayout.addWidget(self.linear_measure)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.subject_overview = QtGui.QToolButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subject_overview.sizePolicy().hasHeightForWidth())
        self.subject_overview.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/some_fibers.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subject_overview.setIcon(icon4)
        self.subject_overview.setIconSize(QtCore.QSize(60, 60))
        self.subject_overview.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.subject_overview.setObjectName(_fromUtf8("subject_overview"))
        self.horizontalLayout_2.addWidget(self.subject_overview)
        self.fmri_explorer = QtGui.QToolButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fmri_explorer.sizePolicy().hasHeightForWidth())
        self.fmri_explorer.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/fmri_explore_small.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fmri_explorer.setIcon(icon5)
        self.fmri_explorer.setIconSize(QtCore.QSize(60, 60))
        self.fmri_explorer.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.fmri_explorer.setObjectName(_fromUtf8("fmri_explorer"))
        self.horizontalLayout_2.addWidget(self.fmri_explorer)
        self.check_registration = QtGui.QToolButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_registration.sizePolicy().hasHeightForWidth())
        self.check_registration.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/check_reg.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check_registration.setIcon(icon6)
        self.check_registration.setIconSize(QtCore.QSize(60, 60))
        self.check_registration.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.check_registration.setObjectName(_fromUtf8("check_registration"))
        self.horizontalLayout_2.addWidget(self.check_registration)
        self.image_slices = QtGui.QToolButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_slices.sizePolicy().hasHeightForWidth())
        self.image_slices.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/braviz_dianita.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.image_slices.setIcon(icon7)
        self.image_slices.setIconSize(QtCore.QSize(60, 60))
        self.image_slices.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.image_slices.setObjectName(_fromUtf8("image_slices"))
        self.horizontalLayout_2.addWidget(self.image_slices)
        self.sample_overview = QtGui.QToolButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_overview.sizePolicy().hasHeightForWidth())
        self.sample_overview.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/sample_overview.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sample_overview.setIcon(icon8)
        self.sample_overview.setIconSize(QtCore.QSize(60, 60))
        self.sample_overview.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.sample_overview.setObjectName(_fromUtf8("sample_overview"))
        self.horizontalLayout_2.addWidget(self.sample_overview)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 2)
        self.horizontalLayout_2.setStretch(4, 2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.correlations = QtGui.QToolButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correlations.sizePolicy().hasHeightForWidth())
        self.correlations.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/correlations_app.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.correlations.setIcon(icon9)
        self.correlations.setIconSize(QtCore.QSize(60, 60))
        self.correlations.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.correlations.setObjectName(_fromUtf8("correlations"))
        self.horizontalLayout_3.addWidget(self.correlations)
        self.anova = QtGui.QToolButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anova.sizePolicy().hasHeightForWidth())
        self.anova.setSizePolicy(sizePolicy)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/baviz_anova.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.anova.setIcon(icon10)
        self.anova.setIconSize(QtCore.QSize(60, 60))
        self.anova.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.anova.setObjectName(_fromUtf8("anova"))
        self.horizontalLayout_3.addWidget(self.anova)
        self.linear_model = QtGui.QToolButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linear_model.sizePolicy().hasHeightForWidth())
        self.linear_model.setSizePolicy(sizePolicy)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/linear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.linear_model.setIcon(icon11)
        self.linear_model.setIconSize(QtCore.QSize(60, 60))
        self.linear_model.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.linear_model.setObjectName(_fromUtf8("linear_model"))
        self.horizontalLayout_3.addWidget(self.linear_model)
        self.histogram = QtGui.QToolButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histogram.sizePolicy().hasHeightForWidth())
        self.histogram.setSizePolicy(sizePolicy)
        self.histogram.setIcon(icon7)
        self.histogram.setIconSize(QtCore.QSize(60, 60))
        self.histogram.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.histogram.setObjectName(_fromUtf8("histogram"))
        self.horizontalLayout_3.addWidget(self.histogram)
        self.subject_bars = QtGui.QToolButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subject_bars.sizePolicy().hasHeightForWidth())
        self.subject_bars.setSizePolicy(sizePolicy)
        self.subject_bars.setIcon(icon7)
        self.subject_bars.setIconSize(QtCore.QSize(60, 60))
        self.subject_bars.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.subject_bars.setObjectName(_fromUtf8("subject_bars"))
        self.horizontalLayout_3.addWidget(self.subject_bars)
        self.parallel_coordinates = QtGui.QToolButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parallel_coordinates.sizePolicy().hasHeightForWidth())
        self.parallel_coordinates.setSizePolicy(sizePolicy)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/parallel_coords_logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.parallel_coordinates.setIcon(icon12)
        self.parallel_coordinates.setIconSize(QtCore.QSize(60, 60))
        self.parallel_coordinates.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.parallel_coordinates.setObjectName(_fromUtf8("parallel_coordinates"))
        self.horizontalLayout_3.addWidget(self.parallel_coordinates)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 2)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 2)
        self.horizontalLayout_3.setStretch(5, 2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.import_data = QtGui.QToolButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_data.sizePolicy().hasHeightForWidth())
        self.import_data.setSizePolicy(sizePolicy)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.import_data.setIcon(icon13)
        self.import_data.setIconSize(QtCore.QSize(60, 60))
        self.import_data.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.import_data.setObjectName(_fromUtf8("import_data"))
        self.horizontalLayout_4.addWidget(self.import_data)
        self.export_data = QtGui.QToolButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_data.sizePolicy().hasHeightForWidth())
        self.export_data.setSizePolicy(sizePolicy)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.export_data.setIcon(icon14)
        self.export_data.setIconSize(QtCore.QSize(60, 60))
        self.export_data.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.export_data.setObjectName(_fromUtf8("export_data"))
        self.horizontalLayout_4.addWidget(self.export_data)
        self.manage_variables = QtGui.QToolButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manage_variables.sizePolicy().hasHeightForWidth())
        self.manage_variables.setSizePolicy(sizePolicy)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manage_variables.setIcon(icon15)
        self.manage_variables.setIconSize(QtCore.QSize(60, 60))
        self.manage_variables.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.manage_variables.setObjectName(_fromUtf8("manage_variables"))
        self.horizontalLayout_4.addWidget(self.manage_variables)
        self.manage_scenarios = QtGui.QToolButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manage_scenarios.sizePolicy().hasHeightForWidth())
        self.manage_scenarios.setSizePolicy(sizePolicy)
        self.manage_scenarios.setIcon(icon)
        self.manage_scenarios.setIconSize(QtCore.QSize(60, 60))
        self.manage_scenarios.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.manage_scenarios.setObjectName(_fromUtf8("manage_scenarios"))
        self.horizontalLayout_4.addWidget(self.manage_scenarios)
        self.manage_subsamples = QtGui.QToolButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manage_subsamples.sizePolicy().hasHeightForWidth())
        self.manage_subsamples.setSizePolicy(sizePolicy)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/kontact_contacts.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manage_subsamples.setIcon(icon16)
        self.manage_subsamples.setIconSize(QtCore.QSize(60, 60))
        self.manage_subsamples.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.manage_subsamples.setObjectName(_fromUtf8("manage_subsamples"))
        self.horizontalLayout_4.addWidget(self.manage_subsamples)
        self.subject_switcher = QtGui.QToolButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subject_switcher.sizePolicy().hasHeightForWidth())
        self.subject_switcher.setSizePolicy(sizePolicy)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/metacontact_online.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subject_switcher.setIcon(icon17)
        self.subject_switcher.setIconSize(QtCore.QSize(60, 60))
        self.subject_switcher.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.subject_switcher.setObjectName(_fromUtf8("subject_switcher"))
        self.horizontalLayout_4.addWidget(self.subject_switcher)
        self.review_history = QtGui.QToolButton(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.review_history.sizePolicy().hasHeightForWidth())
        self.review_history.setSizePolicy(sizePolicy)
        self.review_history.setIcon(icon7)
        self.review_history.setIconSize(QtCore.QSize(60, 60))
        self.review_history.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.review_history.setObjectName(_fromUtf8("review_history"))
        self.horizontalLayout_4.addWidget(self.review_history)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 2)
        self.horizontalLayout_4.setStretch(3, 2)
        self.horizontalLayout_4.setStretch(4, 2)
        self.horizontalLayout_4.setStretch(5, 2)
        self.horizontalLayout_4.setStretch(6, 2)
        self.verticalLayout.addWidget(self.groupBox_4)
        BravizMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(BravizMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        BravizMenu.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(BravizMenu)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BravizMenu.setStatusBar(self.statusbar)
        self.action_about = QtGui.QAction(BravizMenu)
        self.action_about.setObjectName(_fromUtf8("action_about"))
        self.action_usage = QtGui.QAction(BravizMenu)
        self.action_usage.setObjectName(_fromUtf8("action_usage"))
        self.menuHelp.addAction(self.action_about)
        self.menuHelp.addAction(self.action_usage)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(BravizMenu)
        QtCore.QMetaObject.connectSlotsByName(BravizMenu)

    def retranslateUi(self, BravizMenu):
        BravizMenu.setWindowTitle(_translate("BravizMenu", "Braviz Menu", None))
        self.project_label.setText(_translate("BravizMenu", "<Project>", None))
        self.groupBox.setTitle(_translate("BravizMenu", "Measure", None))
        self.roi_builder.setText(_translate("BravizMenu", "Roi Builder", None))
        self.logic_bundles.setText(_translate("BravizMenu", "Logic Bundles", None))
        self.linear_measure.setText(_translate("BravizMenu", "Linear Measure", None))
        self.groupBox_2.setTitle(_translate("BravizMenu", "Spatial Visualization", None))
        self.subject_overview.setText(_translate("BravizMenu", "Subject Overview", None))
        self.fmri_explorer.setText(_translate("BravizMenu", "fMRI Explorer", None))
        self.check_registration.setText(_translate("BravizMenu", "Check Registration", None))
        self.image_slices.setText(_translate("BravizMenu", "Image Slices", None))
        self.sample_overview.setText(_translate("BravizMenu", "Sample Overview", None))
        self.groupBox_3.setTitle(_translate("BravizMenu", "Non-spatial Visualization", None))
        self.correlations.setText(_translate("BravizMenu", "Correlations", None))
        self.anova.setText(_translate("BravizMenu", "Anova", None))
        self.linear_model.setText(_translate("BravizMenu", "Linear Model", None))
        self.histogram.setText(_translate("BravizMenu", "Histogram", None))
        self.subject_bars.setText(_translate("BravizMenu", "Subject Bars", None))
        self.parallel_coordinates.setText(_translate("BravizMenu", "Parallel Coordinates", None))
        self.groupBox_4.setTitle(_translate("BravizMenu", "Utilities", None))
        self.import_data.setText(_translate("BravizMenu", "Import Data", None))
        self.export_data.setText(_translate("BravizMenu", "Export Data", None))
        self.manage_variables.setText(_translate("BravizMenu", "Manage Variables", None))
        self.manage_scenarios.setText(_translate("BravizMenu", "Manage Scenarios", None))
        self.manage_subsamples.setText(_translate("BravizMenu", "Manage Sub-Samples", None))
        self.subject_switcher.setText(_translate("BravizMenu", "Subject Switcher", None))
        self.review_history.setText(_translate("BravizMenu", "Review History", None))
        self.menuHelp.setTitle(_translate("BravizMenu", "Help", None))
        self.action_about.setText(_translate("BravizMenu", "About", None))
        self.action_usage.setText(_translate("BravizMenu", "Braviz Help", None))

import resources_rc
