# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\new_variable_dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NewVariableDialog(object):
    def setupUi(self, NewVariableDialog):
        NewVariableDialog.setObjectName(_fromUtf8("NewVariableDialog"))
        NewVariableDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        NewVariableDialog.resize(887, 504)
        NewVariableDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        NewVariableDialog.setSizeGripEnabled(True)
        NewVariableDialog.setModal(True)
        self.gridLayout = QtGui.QGridLayout(NewVariableDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(NewVariableDialog)
        self.frame.setMinimumSize(QtCore.QSize(340, 0))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout = QtGui.QFormLayout(self.frame_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.var_type_combo = QtGui.QComboBox(self.frame_2)
        self.var_type_combo.setEnabled(True)
        self.var_type_combo.setObjectName(_fromUtf8("var_type_combo"))
        self.var_type_combo.addItem(_fromUtf8(""))
        self.var_type_combo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.var_type_combo)
        self.var_name = QtGui.QLabel(self.frame_2)
        self.var_name.setMaximumSize(QtCore.QSize(16777215, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.var_name.setFont(font)
        self.var_name.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.var_name.setObjectName(_fromUtf8("var_name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.var_name)
        self.var_name_input = QtGui.QLineEdit(self.frame_2)
        self.var_name_input.setObjectName(_fromUtf8("var_name_input"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.var_name_input)
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.var_description = QtGui.QPlainTextEdit(self.frame_2)
        self.var_description.setObjectName(_fromUtf8("var_description"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.var_description)
        self.verticalLayout.addWidget(self.frame_2)
        self.details_frame = QtGui.QStackedWidget(self.frame)
        self.details_frame.setObjectName(_fromUtf8("details_frame"))
        self.nominal_page = QtGui.QWidget()
        self.nominal_page.setObjectName(_fromUtf8("nominal_page"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.nominal_page)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labels_names_table = QtGui.QTableView(self.nominal_page)
        self.labels_names_table.setObjectName(_fromUtf8("labels_names_table"))
        self.labels_names_table.horizontalHeader().setStretchLastSection(True)
        self.labels_names_table.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_3.addWidget(self.labels_names_table)
        self.details_frame.addWidget(self.nominal_page)
        self.real_page = QtGui.QWidget()
        self.real_page.setObjectName(_fromUtf8("real_page"))
        self.gridLayout_3 = QtGui.QGridLayout(self.real_page)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.real_page)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.minimum_val = QtGui.QDoubleSpinBox(self.real_page)
        self.minimum_val.setMaximum(9999.0)
        self.minimum_val.setObjectName(_fromUtf8("minimum_val"))
        self.gridLayout_3.addWidget(self.minimum_val, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.real_page)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 4, 1, 1)
        self.maximum_val = QtGui.QDoubleSpinBox(self.real_page)
        self.maximum_val.setMaximum(9999999.0)
        self.maximum_val.setObjectName(_fromUtf8("maximum_val"))
        self.gridLayout_3.addWidget(self.maximum_val, 0, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self.real_page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.optimum_val = QtGui.QSpinBox(self.real_page)
        self.optimum_val.setMaximum(100)
        self.optimum_val.setObjectName(_fromUtf8("optimum_val"))
        self.gridLayout_3.addWidget(self.optimum_val, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.real_page)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 2, 1, 1)
        self.optimum_real_value = QtGui.QLabel(self.real_page)
        self.optimum_real_value.setObjectName(_fromUtf8("optimum_real_value"))
        self.gridLayout_3.addWidget(self.optimum_real_value, 1, 3, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.real_page)
        self.horizontalSlider.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setPageStep(10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout_3.addWidget(self.horizontalSlider, 2, 0, 1, 6)
        spacerItem1 = QtGui.QSpacerItem(20, 91, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 1)
        self.details_frame.addWidget(self.real_page)
        self.verticalLayout.addWidget(self.details_frame)
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.save_button = QtGui.QPushButton(self.frame_4)
        self.save_button.setEnabled(False)
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.horizontalLayout_2.addWidget(self.save_button)
        self.select_button = QtGui.QPushButton(self.frame_4)
        self.select_button.setEnabled(True)
        self.select_button.setObjectName(_fromUtf8("select_button"))
        self.horizontalLayout_2.addWidget(self.select_button)
        self.verticalLayout.addWidget(self.frame_4)
        self.verticalLayout.setStretch(0, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.values_frame = QtGui.QFrame(NewVariableDialog)
        self.values_frame.setMinimumSize(QtCore.QSize(300, 0))
        self.values_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.values_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.values_frame.setObjectName(_fromUtf8("values_frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.values_frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.values_table = QtGui.QTableView(self.values_frame)
        self.values_table.setObjectName(_fromUtf8("values_table"))
        self.values_table.horizontalHeader().setStretchLastSection(True)
        self.values_table.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.values_table)
        self.gridLayout.addWidget(self.values_frame, 0, 1, 1, 1)
        self.label_2.setBuddy(self.var_type_combo)
        self.var_name.setBuddy(self.var_name_input)
        self.label.setBuddy(self.var_description)
        self.label_4.setBuddy(self.minimum_val)
        self.label_5.setBuddy(self.maximum_val)

        self.retranslateUi(NewVariableDialog)
        self.details_frame.setCurrentIndex(0)
        QtCore.QObject.connect(self.select_button, QtCore.SIGNAL(_fromUtf8("clicked()")), NewVariableDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewVariableDialog)

    def retranslateUi(self, NewVariableDialog):
        NewVariableDialog.setWindowTitle(_translate("NewVariableDialog", "Create New Variable", None))
        self.label_2.setText(_translate("NewVariableDialog", "Type :", None))
        self.var_type_combo.setItemText(0, _translate("NewVariableDialog", "Real", None))
        self.var_type_combo.setItemText(1, _translate("NewVariableDialog", "Nominal", None))
        self.var_name.setText(_translate("NewVariableDialog", "Variable Name: ", None))
        self.label.setText(_translate("NewVariableDialog", "Description :", None))
        self.label_4.setToolTip(_translate("NewVariableDialog", "Select the expected minimum value for this variable", None))
        self.label_4.setText(_translate("NewVariableDialog", "Minimum", None))
        self.label_5.setToolTip(_translate("NewVariableDialog", "Select the expected maximum value for this variable", None))
        self.label_5.setText(_translate("NewVariableDialog", "Maximum", None))
        self.label_3.setToolTip(_translate("NewVariableDialog", "Select the optimal value for this value, the value that would be considered \"good\"", None))
        self.label_3.setText(_translate("NewVariableDialog", "Optimum", None))
        self.optimum_val.setSuffix(_translate("NewVariableDialog", "%", None))
        self.label_6.setText(_translate("NewVariableDialog", " = ", None))
        self.optimum_real_value.setText(_translate("NewVariableDialog", "0", None))
        self.save_button.setText(_translate("NewVariableDialog", "Save", None))
        self.select_button.setText(_translate("NewVariableDialog", "Cancel", None))

