# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\ortho_measure.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OrtoMeasure(object):
    def setupUi(self, OrtoMeasure):
        OrtoMeasure.setObjectName(_fromUtf8("OrtoMeasure"))
        OrtoMeasure.resize(1148, 745)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/measure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OrtoMeasure.setWindowIcon(icon)
        OrtoMeasure.setStyleSheet(_fromUtf8("#sphere_tab{\n"
"    \n"
"    background-image: url(:/icons/circle.png);\n"
"    background-repeat:no-repeat;\n"
"    background-position:center;\n"
"    background-clip:padding;\n"
"    background-origin:padding;\n"
"}"))
        self.centralwidget = QtGui.QWidget(OrtoMeasure)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame_3 = QtGui.QFrame(self.splitter)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_3)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.subject_line_label = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.subject_line_label.setFont(font)
        self.subject_line_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_line_label.setObjectName(_fromUtf8("subject_line_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.subject_line_label)
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.image_combo = QtGui.QComboBox(self.frame_3)
        self.image_combo.setObjectName(_fromUtf8("image_combo"))
        self.image_combo.addItem(_fromUtf8(""))
        self.image_combo.addItem(_fromUtf8(""))
        self.image_combo.addItem(_fromUtf8(""))
        self.image_combo.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.image_combo)
        self.label_17 = QtGui.QLabel(self.frame_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_17)
        self.contrast_combo = QtGui.QComboBox(self.frame_3)
        self.contrast_combo.setObjectName(_fromUtf8("contrast_combo"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.contrast_combo)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(4, QtGui.QFormLayout.FieldRole, spacerItem)
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_2)
        self.axial_check = QtGui.QCheckBox(self.frame_3)
        self.axial_check.setChecked(True)
        self.axial_check.setObjectName(_fromUtf8("axial_check"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.axial_check)
        self.axial_slice = QtGui.QSpinBox(self.frame_3)
        self.axial_slice.setObjectName(_fromUtf8("axial_slice"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.axial_slice)
        self.coronal_check = QtGui.QCheckBox(self.frame_3)
        self.coronal_check.setChecked(True)
        self.coronal_check.setObjectName(_fromUtf8("coronal_check"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.coronal_check)
        self.coronal_slice = QtGui.QSpinBox(self.frame_3)
        self.coronal_slice.setObjectName(_fromUtf8("coronal_slice"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.coronal_slice)
        self.sagital_check = QtGui.QCheckBox(self.frame_3)
        self.sagital_check.setChecked(True)
        self.sagital_check.setObjectName(_fromUtf8("sagital_check"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.sagital_check)
        self.sagital_slice = QtGui.QSpinBox(self.frame_3)
        self.sagital_slice.setObjectName(_fromUtf8("sagital_slice"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.sagital_slice)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(12, QtGui.QFormLayout.FieldRole, spacerItem1)
        self.line = QtGui.QFrame(self.frame_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout_2.setWidget(15, QtGui.QFormLayout.SpanningRole, self.line)
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(18, QtGui.QFormLayout.LabelRole, self.label_8)
        self.measure_name = QtGui.QLineEdit(self.frame_3)
        self.measure_name.setReadOnly(True)
        self.measure_name.setObjectName(_fromUtf8("measure_name"))
        self.formLayout_2.setWidget(18, QtGui.QFormLayout.FieldRole, self.measure_name)
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(19, QtGui.QFormLayout.LabelRole, self.label_7)
        self.measure_label = QtGui.QLineEdit(self.frame_3)
        self.measure_label.setReadOnly(True)
        self.measure_label.setObjectName(_fromUtf8("measure_label"))
        self.formLayout_2.setWidget(19, QtGui.QFormLayout.FieldRole, self.measure_label)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(20, QtGui.QFormLayout.FieldRole, spacerItem2)
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(22, QtGui.QFormLayout.LabelRole, self.label_3)
        self.point_1 = QtGui.QLineEdit(self.frame_3)
        self.point_1.setReadOnly(True)
        self.point_1.setObjectName(_fromUtf8("point_1"))
        self.formLayout_2.setWidget(22, QtGui.QFormLayout.FieldRole, self.point_1)
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(23, QtGui.QFormLayout.LabelRole, self.label_4)
        self.point_2 = QtGui.QLineEdit(self.frame_3)
        self.point_2.setReadOnly(True)
        self.point_2.setObjectName(_fromUtf8("point_2"))
        self.formLayout_2.setWidget(23, QtGui.QFormLayout.FieldRole, self.point_2)
        self.label_11 = QtGui.QLabel(self.frame_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(32, QtGui.QFormLayout.LabelRole, self.label_11)
        self.color_button = QtGui.QPushButton(self.frame_3)
        self.color_button.setEnabled(True)
        self.color_button.setObjectName(_fromUtf8("color_button"))
        self.formLayout_2.setWidget(32, QtGui.QFormLayout.FieldRole, self.color_button)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(33, QtGui.QFormLayout.LabelRole, spacerItem3)
        self.save_line = QtGui.QPushButton(self.frame_3)
        self.save_line.setObjectName(_fromUtf8("save_line"))
        self.formLayout_2.setWidget(34, QtGui.QFormLayout.SpanningRole, self.save_line)
        self.reset_measure = QtGui.QPushButton(self.frame_3)
        self.reset_measure.setObjectName(_fromUtf8("reset_measure"))
        self.formLayout_2.setWidget(36, QtGui.QFormLayout.SpanningRole, self.reset_measure)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(37, QtGui.QFormLayout.LabelRole, spacerItem4)
        self.reset_camera_button = QtGui.QPushButton(self.frame_3)
        self.reset_camera_button.setObjectName(_fromUtf8("reset_camera_button"))
        self.formLayout_2.setWidget(38, QtGui.QFormLayout.SpanningRole, self.reset_camera_button)
        self.reload_button = QtGui.QPushButton(self.frame_3)
        self.reload_button.setObjectName(_fromUtf8("reload_button"))
        self.formLayout_2.setWidget(35, QtGui.QFormLayout.SpanningRole, self.reload_button)
        self.frame = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(600, 0))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.vtk_frame = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_frame.sizePolicy().hasHeightForWidth())
        self.vtk_frame.setSizePolicy(sizePolicy)
        self.vtk_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.vtk_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.vtk_frame.setObjectName(_fromUtf8("vtk_frame"))
        self.verticalLayout_2.addWidget(self.vtk_frame)
        self.frame_2 = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout.addWidget(self.label_15)
        self.subjects_list = QtGui.QListView(self.frame_2)
        self.subjects_list.setAlternatingRowColors(True)
        self.subjects_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.subjects_list.setObjectName(_fromUtf8("subjects_list"))
        self.verticalLayout.addWidget(self.subjects_list)
        self.horizontalLayout.addWidget(self.splitter)
        OrtoMeasure.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(OrtoMeasure)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1148, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        OrtoMeasure.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OrtoMeasure)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        OrtoMeasure.setStatusBar(self.statusbar)
        self.actionSave_Scenario = QtGui.QAction(OrtoMeasure)
        self.actionSave_Scenario.setObjectName(_fromUtf8("actionSave_Scenario"))
        self.actionLoad_Scenario = QtGui.QAction(OrtoMeasure)
        self.actionLoad_Scenario.setObjectName(_fromUtf8("actionLoad_Scenario"))
        self.actionSave_line_as = QtGui.QAction(OrtoMeasure)
        self.actionSave_line_as.setObjectName(_fromUtf8("actionSave_line_as"))
        self.actionSwitch_line = QtGui.QAction(OrtoMeasure)
        self.actionSwitch_line.setObjectName(_fromUtf8("actionSwitch_line"))
        self.menuFile.addAction(self.actionSave_Scenario)
        self.menuFile.addAction(self.actionLoad_Scenario)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_line_as)
        self.menuFile.addAction(self.actionSwitch_line)
        self.menubar.addAction(self.menuFile.menuAction())
        self.label_8.setBuddy(self.measure_name)
        self.label_11.setBuddy(self.color_button)

        self.retranslateUi(OrtoMeasure)
        QtCore.QMetaObject.connectSlotsByName(OrtoMeasure)

    def retranslateUi(self, OrtoMeasure):
        OrtoMeasure.setWindowTitle(_translate("OrtoMeasure", "Braviz Orthogonal Measuring", None))
        self.subject_line_label.setText(_translate("OrtoMeasure", "Subject", None))
        self.label.setText(_translate("OrtoMeasure", "Image: ", None))
        self.image_combo.setItemText(0, _translate("OrtoMeasure", "MRI", None))
        self.image_combo.setItemText(1, _translate("OrtoMeasure", "APARC", None))
        self.image_combo.setItemText(2, _translate("OrtoMeasure", "WMPARC", None))
        self.image_combo.setItemText(3, _translate("OrtoMeasure", "DTI", None))
        self.label_17.setText(_translate("OrtoMeasure", "Contrast:", None))
        self.label_2.setText(_translate("OrtoMeasure", "Slice:", None))
        self.axial_check.setText(_translate("OrtoMeasure", "Axial", None))
        self.coronal_check.setText(_translate("OrtoMeasure", "Coronal", None))
        self.sagital_check.setText(_translate("OrtoMeasure", "Sagital", None))
        self.label_8.setText(_translate("OrtoMeasure", "Measure", None))
        self.measure_name.setText(_translate("OrtoMeasure", "??????", None))
        self.label_7.setText(_translate("OrtoMeasure", "Length:", None))
        self.label_3.setText(_translate("OrtoMeasure", "Point 1:", None))
        self.label_4.setText(_translate("OrtoMeasure", "Point 2:", None))
        self.label_11.setText(_translate("OrtoMeasure", "Color:", None))
        self.color_button.setText(_translate("OrtoMeasure", "Select", None))
        self.save_line.setText(_translate("OrtoMeasure", "Save Measure", None))
        self.reset_measure.setText(_translate("OrtoMeasure", "Reset Measure", None))
        self.reset_camera_button.setText(_translate("OrtoMeasure", "Reset Camera", None))
        self.reload_button.setToolTip(_translate("OrtoMeasure", "Reload line from the database", None))
        self.reload_button.setText(_translate("OrtoMeasure", "Relaod Measure", None))
        self.label_15.setText(_translate("OrtoMeasure", "Subjects", None))
        self.menuFile.setTitle(_translate("OrtoMeasure", "File", None))
        self.actionSave_Scenario.setText(_translate("OrtoMeasure", "Save Scenario", None))
        self.actionLoad_Scenario.setText(_translate("OrtoMeasure", "Load Scenario", None))
        self.actionSave_line_as.setText(_translate("OrtoMeasure", "Save line as...", None))
        self.actionSwitch_line.setText(_translate("OrtoMeasure", "Switch line", None))

import resources_rc
