# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\relation_viewer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RelationshipViewer(object):
    def setupUi(self, RelationshipViewer):
        RelationshipViewer.setObjectName(_fromUtf8("RelationshipViewer"))
        RelationshipViewer.resize(800, 600)
        self.centralwidget = QtGui.QWidget(RelationshipViewer)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.view_source_tree = QtGui.QTreeView(self.tab_3)
        self.view_source_tree.setAlternatingRowColors(True)
        self.view_source_tree.setHeaderHidden(True)
        self.view_source_tree.setObjectName(_fromUtf8("view_source_tree"))
        self.gridLayout_2.addWidget(self.view_source_tree, 1, 1, 1, 1)
        self.view_rel_tree = QtGui.QTreeView(self.tab_3)
        self.view_rel_tree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.view_rel_tree.setAlternatingRowColors(True)
        self.view_rel_tree.setObjectName(_fromUtf8("view_rel_tree"))
        self.view_rel_tree.header().setDefaultSectionSize(200)
        self.view_rel_tree.header().setMinimumSectionSize(100)
        self.gridLayout_2.addWidget(self.view_rel_tree, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.rels_label = QtGui.QLabel(self.tab_3)
        self.rels_label.setObjectName(_fromUtf8("rels_label"))
        self.gridLayout_2.addWidget(self.rels_label, 0, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.add_rel_button = QtGui.QPushButton(self.tab)
        self.add_rel_button.setObjectName(_fromUtf8("add_rel_button"))
        self.gridLayout.addWidget(self.add_rel_button, 2, 1, 1, 1)
        self.add_dest_tree = QtGui.QTreeView(self.tab)
        self.add_dest_tree.setAlternatingRowColors(True)
        self.add_dest_tree.setObjectName(_fromUtf8("add_dest_tree"))
        self.add_dest_tree.header().setVisible(False)
        self.gridLayout.addWidget(self.add_dest_tree, 1, 1, 1, 1)
        self.ambi_check = QtGui.QCheckBox(self.tab)
        self.ambi_check.setObjectName(_fromUtf8("ambi_check"))
        self.gridLayout.addWidget(self.ambi_check, 2, 0, 1, 1)
        self.add_source_tree = QtGui.QTreeView(self.tab)
        self.add_source_tree.setAlternatingRowColors(True)
        self.add_source_tree.setObjectName(_fromUtf8("add_source_tree"))
        self.add_source_tree.header().setVisible(False)
        self.gridLayout.addWidget(self.add_source_tree, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayout = QtGui.QFormLayout(self.tab_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.db_names_list = QtGui.QListView(self.tab_2)
        self.db_names_list.setObjectName(_fromUtf8("db_names_list"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.db_names_list)
        self.new_var_button = QtGui.QPushButton(self.tab_2)
        self.new_var_button.setObjectName(_fromUtf8("new_var_button"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.new_var_button)
        self.pretty_name = QtGui.QLineEdit(self.tab_2)
        self.pretty_name.setObjectName(_fromUtf8("pretty_name"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.pretty_name)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.add_father_tree = QtGui.QTreeView(self.tab_2)
        self.add_father_tree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.add_father_tree.setProperty("showDropIndicator", False)
        self.add_father_tree.setAlternatingRowColors(True)
        self.add_father_tree.setHeaderHidden(True)
        self.add_father_tree.setObjectName(_fromUtf8("add_father_tree"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.add_father_tree)
        self.add_var_button = QtGui.QPushButton(self.tab_2)
        self.add_var_button.setObjectName(_fromUtf8("add_var_button"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.add_var_button)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.link_tree = QtGui.QTreeView(self.tab_4)
        self.link_tree.setAlternatingRowColors(True)
        self.link_tree.setHeaderHidden(True)
        self.link_tree.setObjectName(_fromUtf8("link_tree"))
        self.gridLayout_3.addWidget(self.link_tree, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.link_var_list = QtGui.QListView(self.tab_4)
        self.link_var_list.setAlternatingRowColors(True)
        self.link_var_list.setObjectName(_fromUtf8("link_var_list"))
        self.gridLayout_3.addWidget(self.link_var_list, 1, 1, 1, 1)
        self.save_link_button = QtGui.QPushButton(self.tab_4)
        self.save_link_button.setObjectName(_fromUtf8("save_link_button"))
        self.gridLayout_3.addWidget(self.save_link_button, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        RelationshipViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RelationshipViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        RelationshipViewer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RelationshipViewer)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        RelationshipViewer.setStatusBar(self.statusbar)

        self.retranslateUi(RelationshipViewer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RelationshipViewer)

    def retranslateUi(self, RelationshipViewer):
        RelationshipViewer.setWindowTitle(_translate("RelationshipViewer", "MainWindow", None))
        self.label.setText(_translate("RelationshipViewer", "Select Source", None))
        self.rels_label.setText(_translate("RelationshipViewer", "Relations from:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("RelationshipViewer", "View Relations", None))
        self.add_rel_button.setText(_translate("RelationshipViewer", "Add Relation", None))
        self.ambi_check.setText(_translate("RelationshipViewer", "Ambiguous?", None))
        self.label_6.setText(_translate("RelationshipViewer", "Origin:", None))
        self.label_7.setText(_translate("RelationshipViewer", "Destination:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("RelationshipViewer", "Add Relation", None))
        self.label_3.setText(_translate("RelationshipViewer", "Father node:", None))
        self.label_5.setText(_translate("RelationshipViewer", "Database Identifier:", None))
        self.new_var_button.setText(_translate("RelationshipViewer", "Create New Database Variable", None))
        self.label_4.setText(_translate("RelationshipViewer", "Pretty Name", None))
        self.add_var_button.setText(_translate("RelationshipViewer", "Add", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("RelationshipViewer", "Add Variable", None))
        self.label_8.setText(_translate("RelationshipViewer", "Database Name", None))
        self.label_2.setText(_translate("RelationshipViewer", "Braint Identifier", None))
        self.save_link_button.setText(_translate("RelationshipViewer", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("RelationshipViewer", "Link Variables", None))

