# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\roi_builder.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RoiBuildApp(object):
    def setupUi(self, RoiBuildApp):
        RoiBuildApp.setObjectName(_fromUtf8("RoiBuildApp"))
        RoiBuildApp.resize(1172, 697)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/roi_builder.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        RoiBuildApp.setWindowIcon(icon)
        RoiBuildApp.setStyleSheet(_fromUtf8("#sphere_tab{\n"
"    \n"
"    background-image: url(:/icons/circle.png);\n"
"    background-repeat:no-repeat;\n"
"    background-position:center;\n"
"    background-clip:padding;\n"
"    background-origin:padding;\n"
"}"))
        self.centralwidget = QtGui.QWidget(RoiBuildApp)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.ContextTab = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ContextTab.sizePolicy().hasHeightForWidth())
        self.ContextTab.setSizePolicy(sizePolicy)
        self.ContextTab.setObjectName(_fromUtf8("ContextTab"))
        self.sphere_tab = QtGui.QWidget()
        self.sphere_tab.setObjectName(_fromUtf8("sphere_tab"))
        self.formLayout_3 = QtGui.QFormLayout(self.sphere_tab)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(self.sphere_tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.sphere_tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.sphere_space = QtGui.QLineEdit(self.sphere_tab)
        self.sphere_space.setReadOnly(True)
        self.sphere_space.setObjectName(_fromUtf8("sphere_space"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.sphere_space)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_3.setItem(2, QtGui.QFormLayout.LabelRole, spacerItem)
        self.line_2 = QtGui.QFrame(self.sphere_tab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.SpanningRole, self.line_2)
        self.subject_sphere_label = QtGui.QLabel(self.sphere_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.subject_sphere_label.setFont(font)
        self.subject_sphere_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_sphere_label.setObjectName(_fromUtf8("subject_sphere_label"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.SpanningRole, self.subject_sphere_label)
        self.label_7 = QtGui.QLabel(self.sphere_tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.sphere_radius = QtGui.QDoubleSpinBox(self.sphere_tab)
        self.sphere_radius.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sphere_radius.setMinimum(1.0)
        self.sphere_radius.setMaximum(1000.0)
        self.sphere_radius.setProperty("value", 10.0)
        self.sphere_radius.setObjectName(_fromUtf8("sphere_radius"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.sphere_radius)
        self.label_3 = QtGui.QLabel(self.sphere_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.sphere_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_4)
        self.sphere_x = QtGui.QDoubleSpinBox(self.sphere_tab)
        self.sphere_x.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sphere_x.setMinimum(-1000.0)
        self.sphere_x.setMaximum(1000.0)
        self.sphere_x.setObjectName(_fromUtf8("sphere_x"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.sphere_x)
        self.label_5 = QtGui.QLabel(self.sphere_tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_5)
        self.sphere_y = QtGui.QDoubleSpinBox(self.sphere_tab)
        self.sphere_y.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sphere_y.setMinimum(-1000.0)
        self.sphere_y.setMaximum(1000.0)
        self.sphere_y.setObjectName(_fromUtf8("sphere_y"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.sphere_y)
        self.label_6 = QtGui.QLabel(self.sphere_tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_6)
        self.sphere_z = QtGui.QDoubleSpinBox(self.sphere_tab)
        self.sphere_z.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sphere_z.setMinimum(-1000.0)
        self.sphere_z.setMaximum(1000.0)
        self.sphere_z.setObjectName(_fromUtf8("sphere_z"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.FieldRole, self.sphere_z)
        self.copy_from_cursor_button = QtGui.QPushButton(self.sphere_tab)
        self.copy_from_cursor_button.setObjectName(_fromUtf8("copy_from_cursor_button"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.SpanningRole, self.copy_from_cursor_button)
        self.save_sphere = QtGui.QPushButton(self.sphere_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.save_sphere.setFont(font)
        self.save_sphere.setAutoDefault(True)
        self.save_sphere.setDefault(True)
        self.save_sphere.setObjectName(_fromUtf8("save_sphere"))
        self.formLayout_3.setWidget(13, QtGui.QFormLayout.SpanningRole, self.save_sphere)
        self.line = QtGui.QFrame(self.sphere_tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout_3.setWidget(15, QtGui.QFormLayout.SpanningRole, self.line)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_3.setItem(17, QtGui.QFormLayout.LabelRole, spacerItem1)
        self.label_10 = QtGui.QLabel(self.sphere_tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_3.setWidget(18, QtGui.QFormLayout.LabelRole, self.label_10)
        self.sphere_opac = QtGui.QSlider(self.sphere_tab)
        self.sphere_opac.setMaximum(100)
        self.sphere_opac.setProperty("value", 100)
        self.sphere_opac.setOrientation(QtCore.Qt.Horizontal)
        self.sphere_opac.setObjectName(_fromUtf8("sphere_opac"))
        self.formLayout_3.setWidget(19, QtGui.QFormLayout.SpanningRole, self.sphere_opac)
        self.label_11 = QtGui.QLabel(self.sphere_tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_3.setWidget(20, QtGui.QFormLayout.LabelRole, self.label_11)
        self.color_button = QtGui.QPushButton(self.sphere_tab)
        self.color_button.setEnabled(True)
        self.color_button.setObjectName(_fromUtf8("color_button"))
        self.formLayout_3.setWidget(20, QtGui.QFormLayout.FieldRole, self.color_button)
        self.label_12 = QtGui.QLabel(self.sphere_tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_3.setWidget(21, QtGui.QFormLayout.LabelRole, self.label_12)
        self.sphere_rep = QtGui.QComboBox(self.sphere_tab)
        self.sphere_rep.setObjectName(_fromUtf8("sphere_rep"))
        self.sphere_rep.addItem(_fromUtf8(""))
        self.sphere_rep.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(21, QtGui.QFormLayout.FieldRole, self.sphere_rep)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_3.setItem(22, QtGui.QFormLayout.FieldRole, spacerItem2)
        self.show_fibers_check = QtGui.QCheckBox(self.sphere_tab)
        self.show_fibers_check.setObjectName(_fromUtf8("show_fibers_check"))
        self.formLayout_3.setWidget(23, QtGui.QFormLayout.FieldRole, self.show_fibers_check)
        self.mean_inside_label = QtGui.QLabel(self.sphere_tab)
        self.mean_inside_label.setObjectName(_fromUtf8("mean_inside_label"))
        self.formLayout_3.setWidget(28, QtGui.QFormLayout.LabelRole, self.mean_inside_label)
        self.mean_inside_text = QtGui.QLineEdit(self.sphere_tab)
        self.mean_inside_text.setEnabled(False)
        self.mean_inside_text.setReadOnly(True)
        self.mean_inside_text.setObjectName(_fromUtf8("mean_inside_text"))
        self.formLayout_3.setWidget(28, QtGui.QFormLayout.FieldRole, self.mean_inside_text)
        self.inside_check = QtGui.QCheckBox(self.sphere_tab)
        self.inside_check.setObjectName(_fromUtf8("inside_check"))
        self.formLayout_3.setWidget(27, QtGui.QFormLayout.SpanningRole, self.inside_check)
        self.label_18 = QtGui.QLabel(self.sphere_tab)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_3.setWidget(29, QtGui.QFormLayout.LabelRole, self.label_18)
        self.mean_fa = QtGui.QLineEdit(self.sphere_tab)
        self.mean_fa.setEnabled(False)
        self.mean_fa.setReadOnly(True)
        self.mean_fa.setObjectName(_fromUtf8("mean_fa"))
        self.formLayout_3.setWidget(29, QtGui.QFormLayout.FieldRole, self.mean_fa)
        self.label_19 = QtGui.QLabel(self.sphere_tab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_3.setWidget(30, QtGui.QFormLayout.LabelRole, self.label_19)
        self.mean_md = QtGui.QLineEdit(self.sphere_tab)
        self.mean_md.setEnabled(False)
        self.mean_md.setReadOnly(True)
        self.mean_md.setObjectName(_fromUtf8("mean_md"))
        self.formLayout_3.setWidget(30, QtGui.QFormLayout.FieldRole, self.mean_md)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_3.setItem(26, QtGui.QFormLayout.LabelRole, spacerItem3)
        self.optimize_button = QtGui.QPushButton(self.sphere_tab)
        self.optimize_button.setObjectName(_fromUtf8("optimize_button"))
        self.formLayout_3.setWidget(11, QtGui.QFormLayout.SpanningRole, self.optimize_button)
        self.reload_button = QtGui.QPushButton(self.sphere_tab)
        self.reload_button.setObjectName(_fromUtf8("reload_button"))
        self.formLayout_3.setWidget(12, QtGui.QFormLayout.SpanningRole, self.reload_button)
        self.sphere_name_combo = QtGui.QComboBox(self.sphere_tab)
        self.sphere_name_combo.setObjectName(_fromUtf8("sphere_name_combo"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.sphere_name_combo)
        self.ContextTab.addTab(self.sphere_tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayout = QtGui.QFormLayout(self.tab_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.image_combo = QtGui.QComboBox(self.tab_2)
        self.image_combo.setObjectName(_fromUtf8("image_combo"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.image_combo)
        self.axial_check = QtGui.QCheckBox(self.tab_2)
        self.axial_check.setChecked(True)
        self.axial_check.setObjectName(_fromUtf8("axial_check"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.axial_check)
        self.coronal_check = QtGui.QCheckBox(self.tab_2)
        self.coronal_check.setChecked(False)
        self.coronal_check.setObjectName(_fromUtf8("coronal_check"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.coronal_check)
        self.sagital_check = QtGui.QCheckBox(self.tab_2)
        self.sagital_check.setChecked(False)
        self.sagital_check.setObjectName(_fromUtf8("sagital_check"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.sagital_check)
        self.axial_slice = QtGui.QSpinBox(self.tab_2)
        self.axial_slice.setObjectName(_fromUtf8("axial_slice"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.axial_slice)
        self.coronal_slice = QtGui.QSpinBox(self.tab_2)
        self.coronal_slice.setObjectName(_fromUtf8("coronal_slice"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.coronal_slice)
        self.sagital_slice = QtGui.QSpinBox(self.tab_2)
        self.sagital_slice.setObjectName(_fromUtf8("sagital_slice"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.sagital_slice)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.SpanningRole, self.line_3)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_13)
        self.surface_combo = QtGui.QComboBox(self.tab_2)
        self.surface_combo.setObjectName(_fromUtf8("surface_combo"))
        self.surface_combo.addItem(_fromUtf8(""))
        self.surface_combo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.surface_combo)
        self.left_cortex_check = QtGui.QCheckBox(self.tab_2)
        self.left_cortex_check.setObjectName(_fromUtf8("left_cortex_check"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.left_cortex_check)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_14)
        self.scalar_combo = QtGui.QComboBox(self.tab_2)
        self.scalar_combo.setObjectName(_fromUtf8("scalar_combo"))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.scalar_combo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.scalar_combo)
        self.right_cortex_check = QtGui.QCheckBox(self.tab_2)
        self.right_cortex_check.setObjectName(_fromUtf8("right_cortex_check"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.right_cortex_check)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.SpanningRole, self.label_16)
        self.cortex_opac = QtGui.QSlider(self.tab_2)
        self.cortex_opac.setMaximum(100)
        self.cortex_opac.setProperty("value", 100)
        self.cortex_opac.setTracking(False)
        self.cortex_opac.setOrientation(QtCore.Qt.Horizontal)
        self.cortex_opac.setObjectName(_fromUtf8("cortex_opac"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.SpanningRole, self.cortex_opac)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.contrast_combo = QtGui.QComboBox(self.tab_2)
        self.contrast_combo.setObjectName(_fromUtf8("contrast_combo"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.contrast_combo)
        self.ContextTab.addTab(self.tab_2, _fromUtf8(""))
        self.frame = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(600, 0))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.vtk_frame = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_frame.sizePolicy().hasHeightForWidth())
        self.vtk_frame.setSizePolicy(sizePolicy)
        self.vtk_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.vtk_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.vtk_frame.setObjectName(_fromUtf8("vtk_frame"))
        self.verticalLayout_2.addWidget(self.vtk_frame)
        self.frame_2 = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_15 = QtGui.QLabel(self.frame_2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout.addWidget(self.label_15)
        self.subjects_list = QtGui.QListView(self.frame_2)
        self.subjects_list.setAlternatingRowColors(True)
        self.subjects_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.subjects_list.setObjectName(_fromUtf8("subjects_list"))
        self.verticalLayout.addWidget(self.subjects_list)
        self.load_sample = QtGui.QPushButton(self.frame_2)
        self.load_sample.setObjectName(_fromUtf8("load_sample"))
        self.verticalLayout.addWidget(self.load_sample)
        self.extrapolate_button = QtGui.QPushButton(self.frame_2)
        self.extrapolate_button.setObjectName(_fromUtf8("extrapolate_button"))
        self.verticalLayout.addWidget(self.extrapolate_button)
        self.horizontalLayout.addWidget(self.splitter)
        RoiBuildApp.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RoiBuildApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1172, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        RoiBuildApp.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RoiBuildApp)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        RoiBuildApp.setStatusBar(self.statusbar)
        self.actionSave_Scenario = QtGui.QAction(RoiBuildApp)
        self.actionSave_Scenario.setObjectName(_fromUtf8("actionSave_Scenario"))
        self.actionLoad_Scenario = QtGui.QAction(RoiBuildApp)
        self.actionLoad_Scenario.setObjectName(_fromUtf8("actionLoad_Scenario"))
        self.actionSave_sphere_as = QtGui.QAction(RoiBuildApp)
        self.actionSave_sphere_as.setObjectName(_fromUtf8("actionSave_sphere_as"))
        self.actionExport_ROI = QtGui.QAction(RoiBuildApp)
        self.actionExport_ROI.setObjectName(_fromUtf8("actionExport_ROI"))
        self.actionSwitch_sphere = QtGui.QAction(RoiBuildApp)
        self.actionSwitch_sphere.setObjectName(_fromUtf8("actionSwitch_sphere"))
        self.menuFile.addAction(self.actionSave_Scenario)
        self.menuFile.addAction(self.actionLoad_Scenario)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_sphere_as)
        self.menuFile.addAction(self.actionSwitch_sphere)
        self.menuFile.addAction(self.actionExport_ROI)
        self.menubar.addAction(self.menuFile.menuAction())
        self.label_9.setBuddy(self.sphere_space)
        self.label_7.setBuddy(self.sphere_radius)
        self.label_4.setBuddy(self.sphere_x)
        self.label_5.setBuddy(self.sphere_y)
        self.label_6.setBuddy(self.sphere_z)
        self.label_10.setBuddy(self.sphere_opac)
        self.label_11.setBuddy(self.color_button)
        self.label_12.setBuddy(self.sphere_rep)

        self.retranslateUi(RoiBuildApp)
        self.ContextTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RoiBuildApp)

    def retranslateUi(self, RoiBuildApp):
        RoiBuildApp.setWindowTitle(_translate("RoiBuildApp", "Braviz Roi Builder", None))
        self.label_8.setText(_translate("RoiBuildApp", "Sphere:", None))
        self.label_9.setText(_translate("RoiBuildApp", "Coords:", None))
        self.sphere_space.setText(_translate("RoiBuildApp", "Subject", None))
        self.subject_sphere_label.setText(_translate("RoiBuildApp", "Subject", None))
        self.label_7.setText(_translate("RoiBuildApp", "Radius:", None))
        self.label_3.setText(_translate("RoiBuildApp", "Center:", None))
        self.label_4.setText(_translate("RoiBuildApp", "x", None))
        self.label_5.setText(_translate("RoiBuildApp", "y", None))
        self.label_6.setText(_translate("RoiBuildApp", "z", None))
        self.copy_from_cursor_button.setToolTip(_translate("RoiBuildApp", "Move sphere center to cursor(\"c\")", None))
        self.copy_from_cursor_button.setText(_translate("RoiBuildApp", "Copy from cursor", None))
        self.save_sphere.setToolTip(_translate("RoiBuildApp", "Save the current sphere (\"s\")", None))
        self.save_sphere.setText(_translate("RoiBuildApp", "Save sphere", None))
        self.label_10.setText(_translate("RoiBuildApp", "Opacity:", None))
        self.label_11.setText(_translate("RoiBuildApp", "Color:", None))
        self.color_button.setText(_translate("RoiBuildApp", "Select", None))
        self.label_12.setText(_translate("RoiBuildApp", "Repr:", None))
        self.sphere_rep.setItemText(0, _translate("RoiBuildApp", "Solid", None))
        self.sphere_rep.setItemText(1, _translate("RoiBuildApp", "WireFrame", None))
        self.show_fibers_check.setText(_translate("RoiBuildApp", "Show fibers", None))
        self.mean_inside_label.setText(_translate("RoiBuildApp", "Mean IMG:", None))
        self.mean_inside_text.setPlaceholderText(_translate("RoiBuildApp", "<Mean Inside Sphere>", None))
        self.inside_check.setText(_translate("RoiBuildApp", "Calculate value inside ROI", None))
        self.label_18.setText(_translate("RoiBuildApp", "Mean FA:", None))
        self.mean_fa.setPlaceholderText(_translate("RoiBuildApp", "<Mean Inside Sphere>", None))
        self.label_19.setText(_translate("RoiBuildApp", "Mean MD:", None))
        self.mean_md.setPlaceholderText(_translate("RoiBuildApp", "<Mean Inside Sphere>", None))
        self.optimize_button.setToolTip(_translate("RoiBuildApp", "Optimize position of current sphere (\"o\")", None))
        self.optimize_button.setText(_translate("RoiBuildApp", "Optimize", None))
        self.reload_button.setToolTip(_translate("RoiBuildApp", "Reload the sphere from the database", None))
        self.reload_button.setText(_translate("RoiBuildApp", "Reload", None))
        self.ContextTab.setTabText(self.ContextTab.indexOf(self.sphere_tab), _translate("RoiBuildApp", "Sphere", None))
        self.label.setText(_translate("RoiBuildApp", "Image: ", None))
        self.axial_check.setText(_translate("RoiBuildApp", "Axial", None))
        self.coronal_check.setText(_translate("RoiBuildApp", "Coronal", None))
        self.sagital_check.setText(_translate("RoiBuildApp", "Sagital", None))
        self.label_2.setText(_translate("RoiBuildApp", "Slice:", None))
        self.label_13.setText(_translate("RoiBuildApp", "Cortex:", None))
        self.surface_combo.setItemText(0, _translate("RoiBuildApp", "Pial", None))
        self.surface_combo.setItemText(1, _translate("RoiBuildApp", "White", None))
        self.left_cortex_check.setText(_translate("RoiBuildApp", "Left", None))
        self.label_14.setText(_translate("RoiBuildApp", "Scalars:", None))
        self.scalar_combo.setItemText(0, _translate("RoiBuildApp", "Curv", None))
        self.scalar_combo.setItemText(1, _translate("RoiBuildApp", "Average  curv.", None))
        self.scalar_combo.setItemText(2, _translate("RoiBuildApp", "Area", None))
        self.scalar_combo.setItemText(3, _translate("RoiBuildApp", "Thickness", None))
        self.scalar_combo.setItemText(4, _translate("RoiBuildApp", "Sulc", None))
        self.scalar_combo.setItemText(5, _translate("RoiBuildApp", "Parcellation", None))
        self.scalar_combo.setItemText(6, _translate("RoiBuildApp", "Parcellation 2009", None))
        self.scalar_combo.setItemText(7, _translate("RoiBuildApp", "Parcellation DKT", None))
        self.scalar_combo.setItemText(8, _translate("RoiBuildApp", "Broadman Area", None))
        self.right_cortex_check.setText(_translate("RoiBuildApp", "Right", None))
        self.label_16.setText(_translate("RoiBuildApp", "Opacity", None))
        self.label_17.setText(_translate("RoiBuildApp", "Contrast:", None))
        self.ContextTab.setTabText(self.ContextTab.indexOf(self.tab_2), _translate("RoiBuildApp", "Context", None))
        self.label_15.setText(_translate("RoiBuildApp", "Subjects", None))
        self.load_sample.setText(_translate("RoiBuildApp", "Load Sample", None))
        self.extrapolate_button.setText(_translate("RoiBuildApp", "Extrapolate", None))
        self.menuFile.setTitle(_translate("RoiBuildApp", "File", None))
        self.actionSave_Scenario.setText(_translate("RoiBuildApp", "Save Scenario", None))
        self.actionLoad_Scenario.setText(_translate("RoiBuildApp", "Load Scenario", None))
        self.actionSave_sphere_as.setText(_translate("RoiBuildApp", "Save sphere as...", None))
        self.actionExport_ROI.setText(_translate("RoiBuildApp", "Export ROI", None))
        self.actionSwitch_sphere.setText(_translate("RoiBuildApp", "Switch sphere", None))

import resources_rc
