# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\sample_overview.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SampleOverview(object):
    def setupUi(self, SampleOverview):
        SampleOverview.setObjectName(_fromUtf8("SampleOverview"))
        SampleOverview.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/sample_overview.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        SampleOverview.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(SampleOverview)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.view = QtGui.QFrame(self.centralwidget)
        self.view.setFrameShape(QtGui.QFrame.NoFrame)
        self.view.setFrameShadow(QtGui.QFrame.Raised)
        self.view.setObjectName(_fromUtf8("view"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.view)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.row_container = QtGui.QFrame(self.view)
        self.row_container.setFrameShape(QtGui.QFrame.NoFrame)
        self.row_container.setFrameShadow(QtGui.QFrame.Raised)
        self.row_container.setObjectName(_fromUtf8("row_container"))
        self.horizontalLayout_2.addWidget(self.row_container)
        self.plot_1 = QtGui.QFrame(self.view)
        self.plot_1.setMinimumSize(QtCore.QSize(400, 0))
        self.plot_1.setFrameShape(QtGui.QFrame.NoFrame)
        self.plot_1.setFrameShadow(QtGui.QFrame.Raised)
        self.plot_1.setObjectName(_fromUtf8("plot_1"))
        self.horizontalLayout_2.addWidget(self.plot_1)
        self.horizontalLayout_2.setStretch(0, 9)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.view)
        self.control = QtGui.QFrame(self.centralwidget)
        self.control.setFrameShape(QtGui.QFrame.NoFrame)
        self.control.setFrameShadow(QtGui.QFrame.Raised)
        self.control.setObjectName(_fromUtf8("control"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.control)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(self.control)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.nomina_combo = QtGui.QComboBox(self.frame)
        self.nomina_combo.setObjectName(_fromUtf8("nomina_combo"))
        self.nomina_combo.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.nomina_combo)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(self.control)
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.camera_combo = QtGui.QComboBox(self.frame_3)
        self.camera_combo.setObjectName(_fromUtf8("camera_combo"))
        self.camera_combo.addItem(_fromUtf8(""))
        self.camera_combo.addItem(_fromUtf8(""))
        self.camera_combo.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.camera_combo)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.control)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_4 = QtGui.QLabel(self.frame_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_5.addWidget(self.label_4)
        self.space_combo = QtGui.QComboBox(self.frame_4)
        self.space_combo.setObjectName(_fromUtf8("space_combo"))
        self.space_combo.addItem(_fromUtf8(""))
        self.space_combo.addItem(_fromUtf8(""))
        self.space_combo.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.space_combo)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_2 = QtGui.QFrame(self.control)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.rational_combo = QtGui.QComboBox(self.frame_2)
        self.rational_combo.setObjectName(_fromUtf8("rational_combo"))
        self.rational_combo.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.rational_combo)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.control)
        SampleOverview.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SampleOverview)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuReceive_Samples = QtGui.QMenu(self.menuFile)
        self.menuReceive_Samples.setObjectName(_fromUtf8("menuReceive_Samples"))
        SampleOverview.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SampleOverview)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SampleOverview.setStatusBar(self.statusbar)
        self.action_save_scenario = QtGui.QAction(SampleOverview)
        self.action_save_scenario.setObjectName(_fromUtf8("action_save_scenario"))
        self.action_load_visualization = QtGui.QAction(SampleOverview)
        self.action_load_visualization.setObjectName(_fromUtf8("action_load_visualization"))
        self.action_load_scenario = QtGui.QAction(SampleOverview)
        self.action_load_scenario.setObjectName(_fromUtf8("action_load_scenario"))
        self.action_screenshot = QtGui.QAction(SampleOverview)
        self.action_screenshot.setObjectName(_fromUtf8("action_screenshot"))
        self.actionSelect_sample = QtGui.QAction(SampleOverview)
        self.actionSelect_sample.setObjectName(_fromUtf8("actionSelect_sample"))
        self.actionModify_sample = QtGui.QAction(SampleOverview)
        self.actionModify_sample.setObjectName(_fromUtf8("actionModify_sample"))
        self.actionSend_sample = QtGui.QAction(SampleOverview)
        self.actionSend_sample.setObjectName(_fromUtf8("actionSend_sample"))
        self.menuFile.addAction(self.action_save_scenario)
        self.menuFile.addAction(self.action_load_scenario)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_load_visualization)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSelect_sample)
        self.menuFile.addAction(self.actionModify_sample)
        self.menuFile.addAction(self.actionSend_sample)
        self.menuFile.addAction(self.menuReceive_Samples.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(SampleOverview)
        self.nomina_combo.setCurrentIndex(0)
        self.rational_combo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SampleOverview)

    def retranslateUi(self, SampleOverview):
        SampleOverview.setWindowTitle(_translate("SampleOverview", "Braviz: Sample Overview", None))
        self.label.setText(_translate("SampleOverview", "Facet Variable", None))
        self.nomina_combo.setItemText(0, _translate("SampleOverview", "<Select>", None))
        self.label_3.setText(_translate("SampleOverview", "Camera:", None))
        self.camera_combo.setItemText(0, _translate("SampleOverview", "<Select>", None))
        self.camera_combo.setItemText(1, _translate("SampleOverview", "Reset from scenario", None))
        self.camera_combo.setItemText(2, _translate("SampleOverview", "Copy from selected", None))
        self.label_4.setText(_translate("SampleOverview", "Coordinates", None))
        self.space_combo.setItemText(0, _translate("SampleOverview", "Subject", None))
        self.space_combo.setItemText(1, _translate("SampleOverview", "Talairach", None))
        self.space_combo.setItemText(2, _translate("SampleOverview", "Dartel", None))
        self.label_2.setText(_translate("SampleOverview", "Sort Variable", None))
        self.rational_combo.setItemText(0, _translate("SampleOverview", "<Select>", None))
        self.menuFile.setTitle(_translate("SampleOverview", "File", None))
        self.menuReceive_Samples.setTitle(_translate("SampleOverview", "Accept samples", None))
        self.action_save_scenario.setText(_translate("SampleOverview", "Save scenario", None))
        self.action_load_visualization.setText(_translate("SampleOverview", "Load Visualization", None))
        self.action_load_scenario.setText(_translate("SampleOverview", "Load scenario", None))
        self.action_screenshot.setText(_translate("SampleOverview", "Save_screenshot", None))
        self.actionSelect_sample.setText(_translate("SampleOverview", "Load sample", None))
        self.actionModify_sample.setText(_translate("SampleOverview", "Modify sample", None))
        self.actionSend_sample.setText(_translate("SampleOverview", "Send sample", None))

import resources_rc
