# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\braviz\braviz\interaction\qt_guis\subject_overview.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_subject_overview(object):
    def setupUi(self, subject_overview):
        subject_overview.setObjectName(_fromUtf8("subject_overview"))
        subject_overview.resize(857, 658)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/some_fibers.PNG")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        subject_overview.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(subject_overview)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setAutoFillBackground(False)
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.Control_Frame = QtGui.QFrame(self.splitter)
        self.Control_Frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.Control_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Control_Frame.setObjectName(_fromUtf8("Control_Frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Control_Frame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Details = QtGui.QTabWidget(self.Control_Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Details.sizePolicy().hasHeightForWidth())
        self.Details.setSizePolicy(sizePolicy)
        self.Details.setMinimumSize(QtCore.QSize(200, 0))
        self.Details.setTabShape(QtGui.QTabWidget.Rounded)
        self.Details.setElideMode(QtCore.Qt.ElideNone)
        self.Details.setUsesScrollButtons(True)
        self.Details.setMovable(True)
        self.Details.setObjectName(_fromUtf8("Details"))
        self.subjects_tab = QtGui.QWidget()
        self.subjects_tab.setObjectName(_fromUtf8("subjects_tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.subjects_tab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.subjects_table = QtGui.QTableView(self.subjects_tab)
        self.subjects_table.setAlternatingRowColors(True)
        self.subjects_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.subjects_table.setTextElideMode(QtCore.Qt.ElideRight)
        self.subjects_table.setSortingEnabled(True)
        self.subjects_table.setObjectName(_fromUtf8("subjects_table"))
        self.subjects_table.horizontalHeader().setDefaultSectionSize(50)
        self.subjects_table.horizontalHeader().setStretchLastSection(True)
        self.subjects_table.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.subjects_table)
        self.modify_sample_button = QtGui.QPushButton(self.subjects_tab)
        self.modify_sample_button.setEnabled(True)
        self.modify_sample_button.setObjectName(_fromUtf8("modify_sample_button"))
        self.verticalLayout_6.addWidget(self.modify_sample_button)
        self.select_subject_table_vars = QtGui.QPushButton(self.subjects_tab)
        self.select_subject_table_vars.setObjectName(_fromUtf8("select_subject_table_vars"))
        self.verticalLayout_6.addWidget(self.select_subject_table_vars)
        self.Details.addTab(self.subjects_tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.subject_id2 = QtGui.QLabel(self.tab_3)
        self.subject_id2.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_id2.setObjectName(_fromUtf8("subject_id2"))
        self.verticalLayout_5.addWidget(self.subject_id2)
        self.subject_details_table = QtGui.QTableView(self.tab_3)
        self.subject_details_table.setDragEnabled(True)
        self.subject_details_table.setDragDropOverwriteMode(False)
        self.subject_details_table.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.subject_details_table.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.subject_details_table.setAlternatingRowColors(True)
        self.subject_details_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.subject_details_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.subject_details_table.setGridStyle(QtCore.Qt.SolidLine)
        self.subject_details_table.setSortingEnabled(True)
        self.subject_details_table.setObjectName(_fromUtf8("subject_details_table"))
        self.subject_details_table.horizontalHeader().setStretchLastSection(True)
        self.subject_details_table.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.subject_details_table)
        self.select_details_button = QtGui.QPushButton(self.tab_3)
        self.select_details_button.setObjectName(_fromUtf8("select_details_button"))
        self.verticalLayout_5.addWidget(self.select_details_button)
        self.comments = QtGui.QLabel(self.tab_3)
        self.comments.setAlignment(QtCore.Qt.AlignCenter)
        self.comments.setObjectName(_fromUtf8("comments"))
        self.verticalLayout_5.addWidget(self.comments)
        self.comments_box = QtGui.QPlainTextEdit(self.tab_3)
        self.comments_box.setObjectName(_fromUtf8("comments_box"))
        self.verticalLayout_5.addWidget(self.comments_box)
        self.comments_save = QtGui.QPushButton(self.tab_3)
        self.comments_save.setObjectName(_fromUtf8("comments_save"))
        self.verticalLayout_5.addWidget(self.comments_save)
        self.verticalLayout_5.setStretch(1, 2)
        self.verticalLayout_5.setStretch(4, 1)
        self.Details.addTab(self.tab_3, _fromUtf8(""))
        self.image_tab = QtGui.QWidget()
        self.image_tab.setObjectName(_fromUtf8("image_tab"))
        self.formLayout_4 = QtGui.QFormLayout(self.image_tab)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_12 = QtGui.QLabel(self.image_tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.image_mod_combo = QtGui.QComboBox(self.image_tab)
        self.image_mod_combo.setObjectName(_fromUtf8("image_mod_combo"))
        self.image_mod_combo.addItem(_fromUtf8(""))
        self.image_mod_combo.addItem(_fromUtf8(""))
        self.image_mod_combo.addItem(_fromUtf8(""))
        self.image_mod_combo.addItem(_fromUtf8(""))
        self.image_mod_combo.addItem(_fromUtf8(""))
        self.image_mod_combo.addItem(_fromUtf8(""))
        self.image_mod_combo.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.image_mod_combo)
        self.label_13 = QtGui.QLabel(self.image_tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_13)
        self.image_orientation = QtGui.QComboBox(self.image_tab)
        self.image_orientation.setObjectName(_fromUtf8("image_orientation"))
        self.image_orientation.addItem(_fromUtf8(""))
        self.image_orientation.addItem(_fromUtf8(""))
        self.image_orientation.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.image_orientation)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_4.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem)
        self.label_14 = QtGui.QLabel(self.image_tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_14)
        self.image_window = QtGui.QDoubleSpinBox(self.image_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_window.sizePolicy().hasHeightForWidth())
        self.image_window.setSizePolicy(sizePolicy)
        self.image_window.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.image_window.setMinimum(-10000.0)
        self.image_window.setMaximum(10000.0)
        self.image_window.setSingleStep(10.0)
        self.image_window.setObjectName(_fromUtf8("image_window"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.image_window)
        self.label_15 = QtGui.QLabel(self.image_tab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_15)
        self.image_level = QtGui.QDoubleSpinBox(self.image_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_level.sizePolicy().hasHeightForWidth())
        self.image_level.setSizePolicy(sizePolicy)
        self.image_level.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.image_level.setMinimum(-10000.0)
        self.image_level.setMaximum(10000.0)
        self.image_level.setSingleStep(10.0)
        self.image_level.setObjectName(_fromUtf8("image_level"))
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.image_level)
        self.reset_window_level = QtGui.QPushButton(self.image_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_window_level.sizePolicy().hasHeightForWidth())
        self.reset_window_level.setSizePolicy(sizePolicy)
        self.reset_window_level.setObjectName(_fromUtf8("reset_window_level"))
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.reset_window_level)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_4.setItem(7, QtGui.QFormLayout.FieldRole, spacerItem1)
        self.label = QtGui.QLabel(self.image_tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_4.setWidget(8, QtGui.QFormLayout.LabelRole, self.label)
        self.slice_spin = QtGui.QSpinBox(self.image_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slice_spin.sizePolicy().hasHeightForWidth())
        self.slice_spin.setSizePolicy(sizePolicy)
        self.slice_spin.setObjectName(_fromUtf8("slice_spin"))
        self.formLayout_4.setWidget(8, QtGui.QFormLayout.FieldRole, self.slice_spin)
        self.slice_slider = QtGui.QSlider(self.image_tab)
        self.slice_slider.setOrientation(QtCore.Qt.Horizontal)
        self.slice_slider.setObjectName(_fromUtf8("slice_slider"))
        self.formLayout_4.setWidget(9, QtGui.QFormLayout.SpanningRole, self.slice_slider)
        self.label_17 = QtGui.QLabel(self.image_tab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.contrast_combo = QtGui.QComboBox(self.image_tab)
        self.contrast_combo.setObjectName(_fromUtf8("contrast_combo"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.contrast_combo)
        self.Details.addTab(self.image_tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.formLayout_6 = QtGui.QFormLayout(self.tab_5)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_19 = QtGui.QLabel(self.tab_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_19)
        self.fmri_paradigm_combo = QtGui.QComboBox(self.tab_5)
        self.fmri_paradigm_combo.setObjectName(_fromUtf8("fmri_paradigm_combo"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.fmri_paradigm_combo)
        self.label_18 = QtGui.QLabel(self.tab_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_18)
        self.fmri_contrast_combo = QtGui.QComboBox(self.tab_5)
        self.fmri_contrast_combo.setEnabled(True)
        self.fmri_contrast_combo.setObjectName(_fromUtf8("fmri_contrast_combo"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.fmri_contrast_combo)
        self.fmri_show_contours_check = QtGui.QCheckBox(self.tab_5)
        self.fmri_show_contours_check.setEnabled(True)
        self.fmri_show_contours_check.setChecked(False)
        self.fmri_show_contours_check.setObjectName(_fromUtf8("fmri_show_contours_check"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.fmri_show_contours_check)
        self.fmri_show_contours_value = QtGui.QDoubleSpinBox(self.tab_5)
        self.fmri_show_contours_value.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        self.fmri_show_contours_value.setDecimals(3)
        self.fmri_show_contours_value.setMinimum(0.0)
        self.fmri_show_contours_value.setSingleStep(0.1)
        self.fmri_show_contours_value.setProperty("value", 5.0)
        self.fmri_show_contours_value.setObjectName(_fromUtf8("fmri_show_contours_value"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.fmri_show_contours_value)
        self.Details.addTab(self.tab_5, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.frame_4 = QtGui.QFrame(self.tab)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.left_right_radio = QtGui.QRadioButton(self.frame_4)
        self.left_right_radio.setChecked(True)
        self.left_right_radio.setObjectName(_fromUtf8("left_right_radio"))
        self.horizontalLayout_3.addWidget(self.left_right_radio)
        self.dom_nondom_radio = QtGui.QRadioButton(self.frame_4)
        self.dom_nondom_radio.setObjectName(_fromUtf8("dom_nondom_radio"))
        self.horizontalLayout_3.addWidget(self.dom_nondom_radio)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.structures_tree = QtGui.QTreeView(self.tab)
        self.structures_tree.setAlternatingRowColors(True)
        self.structures_tree.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.structures_tree.setIndentation(10)
        self.structures_tree.setUniformRowHeights(True)
        self.structures_tree.setAnimated(True)
        self.structures_tree.setHeaderHidden(True)
        self.structures_tree.setObjectName(_fromUtf8("structures_tree"))
        self.verticalLayout_7.addWidget(self.structures_tree)
        self.frame_5 = QtGui.QFrame(self.tab)
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_5)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.frame_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.struct_color_combo = QtGui.QComboBox(self.frame_5)
        self.struct_color_combo.setObjectName(_fromUtf8("struct_color_combo"))
        self.struct_color_combo.addItem(_fromUtf8(""))
        self.struct_color_combo.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.struct_color_combo)
        self.label_5 = QtGui.QLabel(self.frame_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.struct_opacity_slider = QtGui.QSlider(self.frame_5)
        self.struct_opacity_slider.setMaximum(100)
        self.struct_opacity_slider.setProperty("value", 100)
        self.struct_opacity_slider.setTracking(False)
        self.struct_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.struct_opacity_slider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.struct_opacity_slider.setObjectName(_fromUtf8("struct_opacity_slider"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.struct_opacity_slider)
        self.struct_scalar_combo = QtGui.QComboBox(self.frame_5)
        self.struct_scalar_combo.setObjectName(_fromUtf8("struct_scalar_combo"))
        self.struct_scalar_combo.addItem(_fromUtf8(""))
        self.struct_scalar_combo.addItem(_fromUtf8(""))
        self.struct_scalar_combo.addItem(_fromUtf8(""))
        self.struct_scalar_combo.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.struct_scalar_combo)
        self.export_segmentation_to_db = QtGui.QPushButton(self.frame_5)
        self.export_segmentation_to_db.setObjectName(_fromUtf8("export_segmentation_to_db"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.SpanningRole, self.export_segmentation_to_db)
        self.line = QtGui.QFrame(self.frame_5)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.SpanningRole, self.line)
        self.struct_scalar_value = QtGui.QLineEdit(self.frame_5)
        self.struct_scalar_value.setReadOnly(True)
        self.struct_scalar_value.setObjectName(_fromUtf8("struct_scalar_value"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.struct_scalar_value)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.Details.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_8.addWidget(self.label_10)
        self.bundles_list = QtGui.QListView(self.tab_2)
        self.bundles_list.setObjectName(_fromUtf8("bundles_list"))
        self.verticalLayout_8.addWidget(self.bundles_list)
        self.refresh_bundles_button = QtGui.QPushButton(self.tab_2)
        self.refresh_bundles_button.setObjectName(_fromUtf8("refresh_bundles_button"))
        self.verticalLayout_8.addWidget(self.refresh_bundles_button)
        self.frame_6 = QtGui.QFrame(self.tab_2)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame_6)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_26 = QtGui.QLabel(self.frame_6)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_26)
        self.fibers_from_segments_box = QtGui.QComboBox(self.frame_6)
        self.fibers_from_segments_box.setObjectName(_fromUtf8("fibers_from_segments_box"))
        self.fibers_from_segments_box.addItem(_fromUtf8(""))
        self.fibers_from_segments_box.addItem(_fromUtf8(""))
        self.fibers_from_segments_box.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.fibers_from_segments_box)
        self.save_bundle_button = QtGui.QPushButton(self.frame_6)
        self.save_bundle_button.setEnabled(False)
        self.save_bundle_button.setObjectName(_fromUtf8("save_bundle_button"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.save_bundle_button)
        self.label_16 = QtGui.QLabel(self.frame_6)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_16)
        self.tracto_color_combo = QtGui.QComboBox(self.frame_6)
        self.tracto_color_combo.setObjectName(_fromUtf8("tracto_color_combo"))
        self.tracto_color_combo.addItem(_fromUtf8(""))
        self.tracto_color_combo.addItem(_fromUtf8(""))
        self.tracto_color_combo.addItem(_fromUtf8(""))
        self.tracto_color_combo.addItem(_fromUtf8(""))
        self.tracto_color_combo.addItem(_fromUtf8(""))
        self.tracto_color_combo.addItem(_fromUtf8(""))
        self.tracto_color_combo.addItem(_fromUtf8(""))
        self.tracto_color_combo.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.tracto_color_combo)
        self.current_bundle_tag = QtGui.QLabel(self.frame_6)
        self.current_bundle_tag.setObjectName(_fromUtf8("current_bundle_tag"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.SpanningRole, self.current_bundle_tag)
        self.fibers_scalar_combo = QtGui.QComboBox(self.frame_6)
        self.fibers_scalar_combo.setObjectName(_fromUtf8("fibers_scalar_combo"))
        self.fibers_scalar_combo.addItem(_fromUtf8(""))
        self.fibers_scalar_combo.addItem(_fromUtf8(""))
        self.fibers_scalar_combo.addItem(_fromUtf8(""))
        self.fibers_scalar_combo.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.fibers_scalar_combo)
        self.export_fiber_scalars_to_db = QtGui.QPushButton(self.frame_6)
        self.export_fiber_scalars_to_db.setObjectName(_fromUtf8("export_fiber_scalars_to_db"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.SpanningRole, self.export_fiber_scalars_to_db)
        self.line_2 = QtGui.QFrame(self.frame_6)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.SpanningRole, self.line_2)
        self.line_3 = QtGui.QFrame(self.frame_6)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.SpanningRole, self.line_3)
        self.label_6 = QtGui.QLabel(self.frame_6)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.fibers_opacity = QtGui.QSlider(self.frame_6)
        self.fibers_opacity.setMaximum(100)
        self.fibers_opacity.setProperty("value", 100)
        self.fibers_opacity.setTracking(False)
        self.fibers_opacity.setOrientation(QtCore.Qt.Horizontal)
        self.fibers_opacity.setTickPosition(QtGui.QSlider.TicksBelow)
        self.fibers_opacity.setObjectName(_fromUtf8("fibers_opacity"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.fibers_opacity)
        self.show_color_bar_check = QtGui.QCheckBox(self.frame_6)
        self.show_color_bar_check.setObjectName(_fromUtf8("show_color_bar_check"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.show_color_bar_check)
        self.fibers_scalar_value = QtGui.QLineEdit(self.frame_6)
        self.fibers_scalar_value.setReadOnly(True)
        self.fibers_scalar_value.setObjectName(_fromUtf8("fibers_scalar_value"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.FieldRole, self.fibers_scalar_value)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.Details.addTab(self.tab_2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tracula_list = QtGui.QListView(self.tab_6)
        self.tracula_list.setObjectName(_fromUtf8("tracula_list"))
        self.verticalLayout_9.addWidget(self.tracula_list)
        self.label_20 = QtGui.QLabel(self.tab_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_9.addWidget(self.label_20)
        self.tracula_opac = QtGui.QSlider(self.tab_6)
        self.tracula_opac.setMaximum(100)
        self.tracula_opac.setProperty("value", 100)
        self.tracula_opac.setOrientation(QtCore.Qt.Horizontal)
        self.tracula_opac.setObjectName(_fromUtf8("tracula_opac"))
        self.verticalLayout_9.addWidget(self.tracula_opac)
        self.Details.addTab(self.tab_6, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.formLayout_5 = QtGui.QFormLayout(self.tab_4)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_9 = QtGui.QLabel(self.tab_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.surface_left_check = QtGui.QCheckBox(self.tab_4)
        self.surface_left_check.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.surface_left_check.setObjectName(_fromUtf8("surface_left_check"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.surface_left_check)
        self.surface_right_check = QtGui.QCheckBox(self.tab_4)
        self.surface_right_check.setObjectName(_fromUtf8("surface_right_check"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.surface_right_check)
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.surface_select_combo = QtGui.QComboBox(self.tab_4)
        self.surface_select_combo.setObjectName(_fromUtf8("surface_select_combo"))
        self.surface_select_combo.addItem(_fromUtf8(""))
        self.surface_select_combo.addItem(_fromUtf8(""))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.surface_select_combo)
        self.surface_scalars_combo = QtGui.QComboBox(self.tab_4)
        self.surface_scalars_combo.setObjectName(_fromUtf8("surface_scalars_combo"))
        self.surface_scalars_combo.addItem(_fromUtf8(""))
        self.surface_scalars_combo.addItem(_fromUtf8(""))
        self.surface_scalars_combo.addItem(_fromUtf8(""))
        self.surface_scalars_combo.addItem(_fromUtf8(""))
        self.surface_scalars_combo.addItem(_fromUtf8(""))
        self.surface_scalars_combo.addItem(_fromUtf8(""))
        self.surface_scalars_combo.addItem(_fromUtf8(""))
        self.surface_scalars_combo.addItem(_fromUtf8(""))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.surface_scalars_combo)
        self.surface_color_bar_check = QtGui.QCheckBox(self.tab_4)
        self.surface_color_bar_check.setObjectName(_fromUtf8("surface_color_bar_check"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.surface_color_bar_check)
        self.label_11 = QtGui.QLabel(self.tab_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_11)
        self.surf_opacity_slider = QtGui.QSlider(self.tab_4)
        self.surf_opacity_slider.setMaximum(100)
        self.surf_opacity_slider.setProperty("value", 100)
        self.surf_opacity_slider.setTracking(False)
        self.surf_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.surf_opacity_slider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.surf_opacity_slider.setTickInterval(10)
        self.surf_opacity_slider.setObjectName(_fromUtf8("surf_opacity_slider"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.surf_opacity_slider)
        self.Details.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.Details)
        self.groupBox = QtGui.QGroupBox(self.Control_Frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_2 = QtGui.QFrame(self.groupBox)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.formLayout = QtGui.QFormLayout(self.frame_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.space_combo = QtGui.QComboBox(self.frame_2)
        self.space_combo.setObjectName(_fromUtf8("space_combo"))
        self.space_combo.addItem(_fromUtf8(""))
        self.space_combo.addItem(_fromUtf8(""))
        self.space_combo.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.space_combo)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.camera_pos = QtGui.QComboBox(self.frame_2)
        self.camera_pos.setBaseSize(QtCore.QSize(73, 0))
        self.camera_pos.setObjectName(_fromUtf8("camera_pos"))
        self.camera_pos.addItem(_fromUtf8(""))
        self.camera_pos.addItem(_fromUtf8(""))
        self.camera_pos.addItem(_fromUtf8(""))
        self.camera_pos.addItem(_fromUtf8(""))
        self.camera_pos.addItem(_fromUtf8(""))
        self.camera_pos.addItem(_fromUtf8(""))
        self.camera_pos.addItem(_fromUtf8(""))
        self.camera_pos.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.camera_pos)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout.setStretch(0, 1)
        self.view_frame = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view_frame.sizePolicy().hasHeightForWidth())
        self.view_frame.setSizePolicy(sizePolicy)
        self.view_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.view_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.view_frame.setObjectName(_fromUtf8("view_frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.view_frame)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter_2 = QtGui.QSplitter(self.view_frame)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.vtk_frame = QtGui.QFrame(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.vtk_frame.sizePolicy().hasHeightForWidth())
        self.vtk_frame.setSizePolicy(sizePolicy)
        self.vtk_frame.setMinimumSize(QtCore.QSize(200, 0))
        self.vtk_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.vtk_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.vtk_frame.setObjectName(_fromUtf8("vtk_frame"))
        self.frame_3 = QtGui.QFrame(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 36))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 36))
        self.frame_3.setBaseSize(QtCore.QSize(0, 36))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.reload_last_subject = QtGui.QToolButton(self.frame_3)
        self.reload_last_subject.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reload_last_subject.setIcon(icon1)
        self.reload_last_subject.setObjectName(_fromUtf8("reload_last_subject"))
        self.horizontalLayout_2.addWidget(self.reload_last_subject)
        self.previus_subject = QtGui.QToolButton(self.frame_3)
        self.previus_subject.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previus_subject.setIcon(icon2)
        self.previus_subject.setObjectName(_fromUtf8("previus_subject"))
        self.horizontalLayout_2.addWidget(self.previus_subject)
        self.subject_id = QtGui.QLineEdit(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subject_id.sizePolicy().hasHeightForWidth())
        self.subject_id.setSizePolicy(sizePolicy)
        self.subject_id.setMaximumSize(QtCore.QSize(70, 16777215))
        self.subject_id.setBaseSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subject_id.setFont(font)
        self.subject_id.setMaxLength(5)
        self.subject_id.setAlignment(QtCore.Qt.AlignCenter)
        self.subject_id.setObjectName(_fromUtf8("subject_id"))
        self.horizontalLayout_2.addWidget(self.subject_id)
        self.next_subject = QtGui.QToolButton(self.frame_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_subject.setIcon(icon3)
        self.next_subject.setObjectName(_fromUtf8("next_subject"))
        self.horizontalLayout_2.addWidget(self.next_subject)
        self.freeze_subject = QtGui.QToolButton(self.frame_3)
        self.freeze_subject.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/thg-password.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.freeze_subject.setIcon(icon4)
        self.freeze_subject.setCheckable(True)
        self.freeze_subject.setObjectName(_fromUtf8("freeze_subject"))
        self.horizontalLayout_2.addWidget(self.freeze_subject)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.verticalLayout_3.addWidget(self.splitter)
        subject_overview.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(subject_overview)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 857, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAccept_sample = QtGui.QMenu(self.menuFile)
        self.menuAccept_sample.setObjectName(_fromUtf8("menuAccept_sample"))
        subject_overview.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(subject_overview)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        subject_overview.setStatusBar(self.statusbar)
        self.actionSave_scenario = QtGui.QAction(subject_overview)
        self.actionSave_scenario.setObjectName(_fromUtf8("actionSave_scenario"))
        self.actionLoad_scenario = QtGui.QAction(subject_overview)
        self.actionLoad_scenario.setObjectName(_fromUtf8("actionLoad_scenario"))
        self.actionAuto_loop = QtGui.QAction(subject_overview)
        self.actionAuto_loop.setCheckable(True)
        self.actionAuto_loop.setObjectName(_fromUtf8("actionAuto_loop"))
        self.actionLoad_sample = QtGui.QAction(subject_overview)
        self.actionLoad_sample.setObjectName(_fromUtf8("actionLoad_sample"))
        self.actionModify_sample = QtGui.QAction(subject_overview)
        self.actionModify_sample.setObjectName(_fromUtf8("actionModify_sample"))
        self.actionSend_sample = QtGui.QAction(subject_overview)
        self.actionSend_sample.setObjectName(_fromUtf8("actionSend_sample"))
        self.actionTake_screenshot = QtGui.QAction(subject_overview)
        self.actionTake_screenshot.setObjectName(_fromUtf8("actionTake_screenshot"))
        self.menuFile.addAction(self.actionSave_scenario)
        self.menuFile.addAction(self.actionLoad_scenario)
        self.menuFile.addAction(self.actionAuto_loop)
        self.menuFile.addAction(self.actionTake_screenshot)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_sample)
        self.menuFile.addAction(self.actionModify_sample)
        self.menuFile.addAction(self.actionSend_sample)
        self.menuFile.addAction(self.menuAccept_sample.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.label_12.setBuddy(self.image_mod_combo)
        self.label_13.setBuddy(self.image_orientation)
        self.label_14.setBuddy(self.image_window)
        self.label_15.setBuddy(self.image_level)
        self.label.setBuddy(self.slice_spin)
        self.label_19.setBuddy(self.image_mod_combo)
        self.label_3.setBuddy(self.space_combo)
        self.label_4.setBuddy(self.camera_pos)

        self.retranslateUi(subject_overview)
        self.Details.setCurrentIndex(1)
        self.image_mod_combo.setCurrentIndex(1)
        self.image_orientation.setCurrentIndex(2)
        self.fmri_paradigm_combo.setCurrentIndex(-1)
        QtCore.QObject.connect(self.slice_spin, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slice_slider.setValue)
        QtCore.QObject.connect(self.slice_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.slice_spin.setValue)
        QtCore.QMetaObject.connectSlotsByName(subject_overview)

    def retranslateUi(self, subject_overview):
        subject_overview.setWindowTitle(_translate("subject_overview", "Braviz: Subject Overview", None))
        subject_overview.setToolTip(_translate("subject_overview", "Go back to the last subject", None))
        self.modify_sample_button.setText(_translate("subject_overview", "Modify Sample", None))
        self.select_subject_table_vars.setText(_translate("subject_overview", "Select Table Columns", None))
        self.Details.setTabText(self.Details.indexOf(self.subjects_tab), _translate("subject_overview", "Subject", None))
        self.Details.setTabToolTip(self.Details.indexOf(self.subjects_tab), _translate("subject_overview", "Select subject", None))
        self.subject_id2.setText(_translate("subject_overview", "???", None))
        self.select_details_button.setText(_translate("subject_overview", "Select Variables", None))
        self.comments.setText(_translate("subject_overview", "Comments", None))
        self.comments_box.setDocumentTitle(_translate("subject_overview", "Comments", None))
        self.comments_save.setText(_translate("subject_overview", "Save", None))
        self.Details.setTabText(self.Details.indexOf(self.tab_3), _translate("subject_overview", "Details", None))
        self.Details.setTabToolTip(self.Details.indexOf(self.tab_3), _translate("subject_overview", "View all details from the subject", None))
        self.label_12.setText(_translate("subject_overview", "Modality", None))
        self.image_mod_combo.setItemText(0, _translate("subject_overview", "None", None))
        self.image_mod_combo.setItemText(1, _translate("subject_overview", "MRI", None))
        self.image_mod_combo.setItemText(2, _translate("subject_overview", "FA", None))
        self.image_mod_combo.setItemText(3, _translate("subject_overview", "MD", None))
        self.image_mod_combo.setItemText(4, _translate("subject_overview", "DTI", None))
        self.image_mod_combo.setItemText(5, _translate("subject_overview", "APARC", None))
        self.image_mod_combo.setItemText(6, _translate("subject_overview", "WMPARC", None))
        self.label_13.setText(_translate("subject_overview", "Orientation", None))
        self.image_orientation.setItemText(0, _translate("subject_overview", "Axial", None))
        self.image_orientation.setItemText(1, _translate("subject_overview", "Coronal", None))
        self.image_orientation.setItemText(2, _translate("subject_overview", "Sagital", None))
        self.label_14.setText(_translate("subject_overview", "Window", None))
        self.label_15.setText(_translate("subject_overview", "Level", None))
        self.reset_window_level.setText(_translate("subject_overview", "Reset", None))
        self.label.setText(_translate("subject_overview", "Slice", None))
        self.label_17.setText(_translate("subject_overview", "Contrast", None))
        self.Details.setTabText(self.Details.indexOf(self.image_tab), _translate("subject_overview", "Images", None))
        self.Details.setTabToolTip(self.Details.indexOf(self.image_tab), _translate("subject_overview", "Select image to show", None))
        self.label_19.setText(_translate("subject_overview", "Paradigm", None))
        self.label_18.setText(_translate("subject_overview", "Contrast", None))
        self.fmri_show_contours_check.setText(_translate("subject_overview", "Contours", None))
        self.Details.setTabText(self.Details.indexOf(self.tab_5), _translate("subject_overview", "fMRI", None))
        self.Details.setTabToolTip(self.Details.indexOf(self.tab_5), _translate("subject_overview", "fMRI Contours", None))
        self.left_right_radio.setText(_translate("subject_overview", "Left/Right", None))
        self.dom_nondom_radio.setText(_translate("subject_overview", "Dominant/Non-Dominant", None))
        self.label_2.setText(_translate("subject_overview", "Color:", None))
        self.struct_color_combo.setItemText(0, _translate("subject_overview", "Free Surfer", None))
        self.struct_color_combo.setItemText(1, _translate("subject_overview", "Select ...", None))
        self.label_5.setText(_translate("subject_overview", "Opacity: ", None))
        self.struct_scalar_combo.setItemText(0, _translate("subject_overview", "Volume", None))
        self.struct_scalar_combo.setItemText(1, _translate("subject_overview", "Area", None))
        self.struct_scalar_combo.setItemText(2, _translate("subject_overview", "FA inside", None))
        self.struct_scalar_combo.setItemText(3, _translate("subject_overview", "MD inside", None))
        self.export_segmentation_to_db.setText(_translate("subject_overview", "Export to Database", None))
        self.Details.setTabText(self.Details.indexOf(self.tab), _translate("subject_overview", "Segmentation", None))
        self.label_10.setText(_translate("subject_overview", "Bundles", None))
        self.refresh_bundles_button.setText(_translate("subject_overview", "Refresh Bundles List", None))
        self.label_26.setToolTip(_translate("subject_overview", "Add fibers based on the visible segmented structures", None))
        self.label_26.setText(_translate("subject_overview", "From Seg.", None))
        self.fibers_from_segments_box.setItemText(0, _translate("subject_overview", "None", None))
        self.fibers_from_segments_box.setItemText(1, _translate("subject_overview", "Through Any", None))
        self.fibers_from_segments_box.setItemText(2, _translate("subject_overview", "Through All", None))
        self.save_bundle_button.setText(_translate("subject_overview", "Save Bundle", None))
        self.label_16.setText(_translate("subject_overview", "Color:", None))
        self.tracto_color_combo.setItemText(0, _translate("subject_overview", "Orientation", None))
        self.tracto_color_combo.setItemText(1, _translate("subject_overview", "FA (Point)", None))
        self.tracto_color_combo.setItemText(2, _translate("subject_overview", "FA (Line)", None))
        self.tracto_color_combo.setItemText(3, _translate("subject_overview", "MD (Point)", None))
        self.tracto_color_combo.setItemText(4, _translate("subject_overview", "MD (Line)", None))
        self.tracto_color_combo.setItemText(5, _translate("subject_overview", "Length", None))
        self.tracto_color_combo.setItemText(6, _translate("subject_overview", "By Line", None))
        self.tracto_color_combo.setItemText(7, _translate("subject_overview", "By Bundle", None))
        self.current_bundle_tag.setText(_translate("subject_overview", "<No active bundle>", None))
        self.fibers_scalar_combo.setItemText(0, _translate("subject_overview", "Count", None))
        self.fibers_scalar_combo.setItemText(1, _translate("subject_overview", "Mean L", None))
        self.fibers_scalar_combo.setItemText(2, _translate("subject_overview", "Mean FA", None))
        self.fibers_scalar_combo.setItemText(3, _translate("subject_overview", "Mean MD", None))
        self.export_fiber_scalars_to_db.setText(_translate("subject_overview", "Export To Database", None))
        self.label_6.setText(_translate("subject_overview", "Opacity:", None))
        self.show_color_bar_check.setText(_translate("subject_overview", "Show color bar", None))
        self.Details.setTabText(self.Details.indexOf(self.tab_2), _translate("subject_overview", "Tractography", None))
        self.label_20.setText(_translate("subject_overview", "Opacity", None))
        self.Details.setTabText(self.Details.indexOf(self.tab_6), _translate("subject_overview", "Tracula", None))
        self.Details.setTabToolTip(self.Details.indexOf(self.tab_6), _translate("subject_overview", "Tracula bundles", None))
        self.label_7.setText(_translate("subject_overview", "Hemispheres:", None))
        self.label_9.setText(_translate("subject_overview", "Surface:", None))
        self.surface_left_check.setText(_translate("subject_overview", "Left", None))
        self.surface_right_check.setText(_translate("subject_overview", "Right", None))
        self.label_8.setText(_translate("subject_overview", "Scalars:", None))
        self.surface_select_combo.setItemText(0, _translate("subject_overview", "White", None))
        self.surface_select_combo.setItemText(1, _translate("subject_overview", "Pial", None))
        self.surface_scalars_combo.setItemText(0, _translate("subject_overview", "Curv", None))
        self.surface_scalars_combo.setItemText(1, _translate("subject_overview", "Avg. curv", None))
        self.surface_scalars_combo.setItemText(2, _translate("subject_overview", "Thickness", None))
        self.surface_scalars_combo.setItemText(3, _translate("subject_overview", "Sulc", None))
        self.surface_scalars_combo.setItemText(4, _translate("subject_overview", "Parcellation", None))
        self.surface_scalars_combo.setItemText(5, _translate("subject_overview", "Parcellation 2009", None))
        self.surface_scalars_combo.setItemText(6, _translate("subject_overview", "Parcellation DKT", None))
        self.surface_scalars_combo.setItemText(7, _translate("subject_overview", "Broadman area", None))
        self.surface_color_bar_check.setText(_translate("subject_overview", "Show color bar", None))
        self.label_11.setText(_translate("subject_overview", "Opacity: ", None))
        self.Details.setTabText(self.Details.indexOf(self.tab_4), _translate("subject_overview", "Surfaces", None))
        self.groupBox.setTitle(_translate("subject_overview", "View", None))
        self.label_3.setText(_translate("subject_overview", "Coordinates:", None))
        self.space_combo.setItemText(0, _translate("subject_overview", "Subject", None))
        self.space_combo.setItemText(1, _translate("subject_overview", "Talairach", None))
        self.space_combo.setItemText(2, _translate("subject_overview", "Dartel", None))
        self.label_4.setToolTip(_translate("subject_overview", "<html><head/><body><p>Use this box to move camera to a predefined position</p></body></html>", None))
        self.label_4.setText(_translate("subject_overview", "Camera to:", None))
        self.camera_pos.setToolTip(_translate("subject_overview", "<html><head/><body><p>Use this box to reset the camera to predefined position</p></body></html>", None))
        self.camera_pos.setItemText(0, _translate("subject_overview", "<Select>", None))
        self.camera_pos.setItemText(1, _translate("subject_overview", "Default", None))
        self.camera_pos.setItemText(2, _translate("subject_overview", "Left", None))
        self.camera_pos.setItemText(3, _translate("subject_overview", "Right", None))
        self.camera_pos.setItemText(4, _translate("subject_overview", "Front", None))
        self.camera_pos.setItemText(5, _translate("subject_overview", "Back", None))
        self.camera_pos.setItemText(6, _translate("subject_overview", "Top", None))
        self.camera_pos.setItemText(7, _translate("subject_overview", "Bottom", None))
        self.previus_subject.setToolTip(_translate("subject_overview", "Move to previus subject (left arrow)", None))
        self.subject_id.setText(_translate("subject_overview", "093", None))
        self.next_subject.setToolTip(_translate("subject_overview", "Move to next subject (right arrow)", None))
        self.next_subject.setText(_translate("subject_overview", "...", None))
        self.freeze_subject.setToolTip(_translate("subject_overview", "freeze current subject", None))
        self.menuFile.setTitle(_translate("subject_overview", "File", None))
        self.menuAccept_sample.setTitle(_translate("subject_overview", "Accept sample", None))
        self.actionSave_scenario.setText(_translate("subject_overview", "Save scenario", None))
        self.actionLoad_scenario.setText(_translate("subject_overview", "Load scenario", None))
        self.actionAuto_loop.setText(_translate("subject_overview", "Auto loop", None))
        self.actionAuto_loop.setToolTip(_translate("subject_overview", "Automatically loop through the subjects in the table", None))
        self.actionLoad_sample.setText(_translate("subject_overview", "Load sample", None))
        self.actionModify_sample.setText(_translate("subject_overview", "Modify sample", None))
        self.actionSend_sample.setText(_translate("subject_overview", "Send sample", None))
        self.actionTake_screenshot.setText(_translate("subject_overview", "Take screenshot", None))

import resources_rc
